export default [
  {
    thumbnail:
      "https://assets.untappd.com/site/beer_logos/beer-1913702_a1804_sm.jpeg",
    name: "What We Don't See",
    style: "Stout",
    substyle: "Imperial / Double",
    breweryName: "KCBC - Kings County Brewers Collective",
    abv: 8,
    ibu: null,
    score: 3.87162,
    beerUrl:
      "https://untappd.com/b/kcbc-kings-county-brewers-collective-what-we-don-t-see/1913702",
    breweryUrl:
      "https://untappd.com/w/kcbc-kings-county-brewers-collective/167520",
    isVip: false,
    id: 1913702,
    table: 37,
  },
  {
    thumbnail:
      "https://assets.untappd.com/site/beer_logos/beer-3059764_8b9c5_sm.jpeg",
    name: "Savage Crush",
    style: "Sour",
    substyle: "Fruited Gose",
    breweryName: "KCBC - Kings County Brewers Collective",
    abv: 5.2,
    ibu: null,
    score: 3.96684,
    beerUrl:
      "https://untappd.com/b/kcbc-kings-county-brewers-collective-savage-crush/3059764",
    breweryUrl:
      "https://untappd.com/w/kcbc-kings-county-brewers-collective/167520",
    isVip: false,
    id: 3059764,
    table: 37,
  },
  {
    thumbnail:
      "https://assets.untappd.com/site/beer_logos/beer-1541885_cfcc3_sm.jpeg",
    name: "Rugged Snuggle",
    style: "Porter",
    substyle: "Other",
    breweryName: "Twin Elephant Brewing Company",
    abv: 6.4,
    ibu: null,
    score: 3.7978,
    beerUrl:
      "https://untappd.com/b/twin-elephant-brewing-company-rugged-snuggle/1541885",
    breweryUrl: "https://untappd.com/w/twin-elephant-brewing-company/268063",
    isVip: false,
    id: 1541885,
    table: 23,
  },
  {
    thumbnail:
      "https://assets.untappd.com/site/beer_logos/beer-5030496_e1188_sm.jpeg",
    name: "Sour Crusher - Apricot",
    style: "Sour",
    substyle: "Fruited",
    breweryName: "Skygazer Brewing Company",
    abv: 5.5,
    ibu: null,
    score: 3.76894,
    beerUrl:
      "https://untappd.com/b/skygazer-brewing-company-sour-crusher-apricot/5030496",
    breweryUrl: "https://untappd.com/w/skygazer-brewing-company/310900",
    isVip: false,
    id: 5030496,
    table: 44,
  },
  {
    thumbnail:
      "https://assets.untappd.com/site/beer_logos/beer-5058465_499dd_sm.jpeg",
    name: "Titan: Three - Sour IPA - Mango, Apricot, Vanilla Beans & Milk Sugar",
    style: "IPA",
    substyle: "Sour",
    breweryName: "Skygazer Brewing Company",
    abv: 7,
    ibu: null,
    score: 3.95451,
    beerUrl:
      "https://untappd.com/b/skygazer-brewing-company-titan-three-sour-ipa-mango-apricot-vanilla-beans-and-milk-sugar/5058465",
    breweryUrl: "https://untappd.com/w/skygazer-brewing-company/310900",
    isVip: false,
    id: 5058465,
    table: 44,
  },
  {
    thumbnail:
      "https://assets.untappd.com/site/beer_logos/beer-5215862_a874c_sm.jpeg",
    name: "Watercolors Go To's - Cherry Peach",
    style: "Sour",
    substyle: "Fruited",
    breweryName: "Skygazer Brewing Company",
    abv: 5.5,
    ibu: null,
    score: 3.72755,
    beerUrl:
      "https://untappd.com/b/skygazer-brewing-company-watercolors-go-to-s-cherry-peach/5215862",
    breweryUrl: "https://untappd.com/w/skygazer-brewing-company/310900",
    isVip: false,
    id: 5215862,
    table: 44,
  },
  {
    thumbnail:
      "https://assets.untappd.com/site/brewery_logos/brewery-234267_0f9f5.jpeg",
    name: "Little Wild",
    style: "Cider",
    substyle: "Traditional / Apfelwein",
    breweryName: "Brooklyn Cider House",
    abv: 5,
    ibu: null,
    score: 3.75237,
    beerUrl: "https://untappd.com/b/brooklyn-cider-house-little-wild/4259462",
    breweryUrl: "https://untappd.com/w/brooklyn-cider-house/234267",
    isVip: false,
    id: 4259462,
    table: 35,
  },
  {
    thumbnail:
      "https://assets.untappd.com/site/beer_logos/beer-251480_15193_sm.jpeg",
    name: "Sweet Helen’s Blend",
    style: "Cider",
    substyle: "Traditional / Apfelwein",
    breweryName: "Jack's Hard Cider",
    abv: 5,
    ibu: null,
    score: 3.59121,
    beerUrl:
      "https://untappd.com/b/jack-s-hard-cider-sweet-helen-s-blend/251480",
    breweryUrl: "https://untappd.com/w/jack-s-hard-cider/4755",
    isVip: false,
    id: 251480,
    table: 32,
  },
  {
    thumbnail:
      "https://assets.untappd.com/site/beer_logos/beer-4431022_8727e_sm.jpeg",
    name: "Norwegian Sprinter",
    style: "Blonde Ale",
    breweryName: "Buttzville Brewing Company",
    abv: 4.7,
    ibu: 19,
    score: 3.61912,
    beerUrl:
      "https://untappd.com/b/buttzville-brewing-company-norwegian-sprinter/4431022",
    breweryUrl: "https://untappd.com/w/buttzville-brewing-company/500844",
    isVip: false,
    id: 4431022,
    table: 25,
  },
  {
    thumbnail:
      "https://assets.untappd.com/site/brewery_logos/brewery-500844_1a649.jpeg",
    name: "Crack of Dawn",
    style: "Stout",
    substyle: "Coffee",
    breweryName: "Buttzville Brewing Company",
    abv: 8.1,
    ibu: 54,
    score: 3.59297,
    beerUrl:
      "https://untappd.com/b/buttzville-brewing-company-crack-of-dawn/5191468",
    breweryUrl: "https://untappd.com/w/buttzville-brewing-company/500844",
    isVip: false,
    id: 5191468,
    table: 25,
  },
  {
    thumbnail:
      "https://assets.untappd.com/site/brewery_logos/brewery-500844_1a649.jpeg",
    name: "Out of the Saddle",
    style: "Stout",
    substyle: "Other",
    breweryName: "Buttzville Brewing Company",
    abv: 11,
    ibu: 71,
    score: 3.68166,
    beerUrl:
      "https://untappd.com/b/buttzville-brewing-company-out-of-the-saddle/4954947",
    breweryUrl: "https://untappd.com/w/buttzville-brewing-company/500844",
    isVip: false,
    id: 4954947,
    table: 25,
  },
  {
    thumbnail:
      "https://assets.untappd.com/site/beer_logos/beer-3314638_881f3_sm.jpeg",
    name: "Morning Glass",
    style: "Sour",
    substyle: "Other",
    breweryName: "Last Wave Brewing Co.",
    abv: 5.2,
    ibu: null,
    score: 3.92446,
    beerUrl: "https://untappd.com/b/last-wave-brewing-co-morning-glass/3314638",
    breweryUrl: "https://untappd.com/w/last-wave-brewing-co/342748",
    isVip: false,
    id: 3314638,
    table: 61,
  },
  {
    thumbnail:
      "https://assets.untappd.com/site/beer_logos/beer-3139237_15e4a_sm.jpeg",
    name: "Quiver",
    style: "IPA",
    substyle: "American",
    breweryName: "Last Wave Brewing Co.",
    abv: 6.7,
    ibu: 30,
    score: 3.6415,
    beerUrl: "https://untappd.com/b/last-wave-brewing-co-quiver/3139237",
    breweryUrl: "https://untappd.com/w/last-wave-brewing-co/342748",
    isVip: false,
    id: 3139237,
    table: 61,
  },
  {
    thumbnail:
      "https://assets.untappd.com/site/beer_logos/beer-4994462_31ec1_sm.jpeg",
    name: "Inherent Vice Lager",
    style: "Lager",
    substyle: "American",
    breweryName: "Wild Air Beerworks",
    abv: 4.5,
    ibu: 8,
    score: 3.76535,
    beerUrl:
      "https://untappd.com/b/wild-air-beerworks-inherent-vice-lager/4994462",
    breweryUrl: "https://untappd.com/w/wild-air-beerworks/528205",
    isVip: false,
    id: 4994462,
    table: 62,
  },
  {
    thumbnail:
      "https://assets.untappd.com/site/brewery_logos/brewery-528205_5e9ce.jpeg",
    name: "Eternal Fugitive",
    style: "Lager",
    substyle: "Pale",
    breweryName: "Wild Air Beerworks",
    abv: 5.7,
    ibu: null,
    score: 3.74637,
    beerUrl:
      "https://untappd.com/b/wild-air-beerworks-eternal-fugitive/5170826",
    breweryUrl: "https://untappd.com/w/wild-air-beerworks/528205",
    isVip: false,
    id: 5170826,
    table: 62,
  },
  {
    thumbnail:
      "https://assets.untappd.com/site/brewery_logos/brewery-455917_5f261.jpeg",
    name: "Milk & Cookies",
    style: "Stout",
    substyle: "Pastry",
    breweryName: "Ross Brewing Company",
    abv: 6.8,
    ibu: 36,
    score: 3.68485,
    beerUrl:
      "https://untappd.com/b/ross-brewing-company-milk-and-cookies/5204681",
    breweryUrl: "https://untappd.com/w/ross-brewing-company/455917",
    isVip: false,
    id: 5204681,
    table: 39,
  },
  {
    thumbnail:
      "https://assets.untappd.com/site/brewery_logos/brewery-455917_5f261.jpeg",
    name: "Berry Salty",
    style: "Sour",
    substyle: "Fruited",
    breweryName: "Ross Brewing Company",
    abv: 4.1,
    ibu: 4,
    score: 3.70101,
    beerUrl: "https://untappd.com/b/ross-brewing-company-berry-salty/5001327",
    breweryUrl: "https://untappd.com/w/ross-brewing-company/455917",
    isVip: false,
    id: 5001327,
    table: 39,
  },
  {
    thumbnail:
      "https://assets.untappd.com/site/beer_logos/beer-4198339_92c2c_sm.jpeg",
    name: "Brux Royale Belgian Chocolate Stout",
    style: "Stout",
    substyle: "Imperial / Double",
    breweryName: "Ross Brewing Company",
    abv: 11.7,
    ibu: 50,
    score: 3.83881,
    beerUrl:
      "https://untappd.com/b/ross-brewing-company-brux-royale-belgian-chocolate-stout/4198339",
    breweryUrl: "https://untappd.com/w/ross-brewing-company/455917",
    isVip: false,
    id: 4198339,
    table: 39,
  },
  {
    thumbnail:
      "https://assets.untappd.com/site/beer_logos/beer-4429625_e573b_sm.jpeg",
    name: "FishFinder",
    style: "Lager",
    substyle: "Helles",
    breweryName: "Ross Brewing Company",
    abv: 5.2,
    ibu: 19,
    score: 3.72342,
    beerUrl: "https://untappd.com/b/ross-brewing-company-fishfinder/4429625",
    breweryUrl: "https://untappd.com/w/ross-brewing-company/455917",
    isVip: false,
    id: 4429625,
    table: 39,
  },
  {
    thumbnail:
      "https://assets.untappd.com/site/beer_logos/beer-3706383_249cc_sm.jpeg",
    name: "Manasquan Wit",
    style: "Wheat Beer",
    substyle: "Witbier / Blanche",
    breweryName: "Ross Brewing Company",
    abv: 5.1,
    ibu: 16,
    score: 3.68348,
    beerUrl: "https://untappd.com/b/ross-brewing-company-manasquan-wit/3706383",
    breweryUrl: "https://untappd.com/w/ross-brewing-company/455917",
    isVip: false,
    id: 3706383,
    table: 39,
  },
  {
    thumbnail:
      "https://assets.untappd.com/site/beer_logos/beer-3622119_f613c_sm.jpeg",
    name: "Shrewsbury Lager",
    style: "Lager",
    substyle: "American Amber / Red",
    breweryName: "Ross Brewing Company",
    abv: 5.2,
    ibu: 23,
    score: 3.70333,
    beerUrl:
      "https://untappd.com/b/ross-brewing-company-shrewsbury-lager/3622119",
    breweryUrl: "https://untappd.com/w/ross-brewing-company/455917",
    isVip: false,
    id: 3622119,
    table: 39,
  },
  {
    thumbnail:
      "https://assets.untappd.com/site/beer_logos/beer-2059122_d4017_sm.jpeg",
    name: "Navesink IPA",
    style: "IPA",
    substyle: "Imperial / Double",
    breweryName: "Ross Brewing Company",
    abv: 7.8,
    ibu: 78,
    score: 3.68336,
    beerUrl: "https://untappd.com/b/ross-brewing-company-navesink-ipa/2059122",
    breweryUrl: "https://untappd.com/w/ross-brewing-company/455917",
    isVip: false,
    id: 2059122,
    table: 39,
  },
  {
    thumbnail:
      "https://assets.untappd.com/site/brewery_logos/brewery-417861_baea5.jpeg",
    name: "Sublime Prince",
    style: "Lager",
    substyle: "American",
    breweryName: "Hackensack Brewing",
    abv: 5,
    ibu: null,
    score: 3.7087,
    beerUrl: "https://untappd.com/b/hackensack-brewing-sublime-prince/5107460",
    breweryUrl: "https://untappd.com/w/hackensack-brewing/417861",
    isVip: false,
    id: 5107460,
    table: 57,
  },
  {
    thumbnail:
      "https://assets.untappd.com/site/brewery_logos/brewery-417861_baea5.jpeg",
    name: "Palisades Pale Ale",
    style: "Pale Ale",
    substyle: "American",
    breweryName: "Hackensack Brewing",
    abv: 5.1,
    ibu: null,
    score: 3.71915,
    beerUrl:
      "https://untappd.com/b/hackensack-brewing-palisades-pale-ale/5089592",
    breweryUrl: "https://untappd.com/w/hackensack-brewing/417861",
    isVip: false,
    id: 5089592,
    table: 57,
  },
  {
    thumbnail:
      "https://assets.untappd.com/site/brewery_logos/brewery-417861_baea5.jpeg",
    name: "Jersey Common",
    style: "Table Beer",
    breweryName: "Hackensack Brewing",
    abv: 5.1,
    ibu: null,
    score: 3.72977,
    beerUrl: "https://untappd.com/b/hackensack-brewing-jersey-common/5123922",
    breweryUrl: "https://untappd.com/w/hackensack-brewing/417861",
    isVip: false,
    id: 5123922,
    table: 57,
  },
  {
    thumbnail:
      "https://assets.untappd.com/site/brewery_logos/brewery-417861_baea5.jpeg",
    name: "Blizzard of 96",
    style: "Winter Warmer",
    breweryName: "Hackensack Brewing",
    abv: 8.5,
    ibu: 15,
    score: 3.70486,
    beerUrl: "https://untappd.com/b/hackensack-brewing-blizzard-of-96/3069553",
    breweryUrl: "https://untappd.com/w/hackensack-brewing/417861",
    isVip: false,
    id: 3069553,
    table: 57,
  },
  {
    thumbnail:
      "https://assets.untappd.com/site/brewery_logos/brewery-341365_12e41.jpeg",
    name: "Done In A Jiffy",
    style: "Porter",
    substyle: "American",
    breweryName: "ManaFirkin Brewing Co.",
    abv: 5.8,
    ibu: 34,
    score: 3.92265,
    beerUrl:
      "https://untappd.com/b/manafirkin-brewing-co-done-in-a-jiffy/3050196",
    breweryUrl: "https://untappd.com/w/manafirkin-brewing-co/341365",
    isVip: false,
    id: 3050196,
    table: 20,
  },
  {
    thumbnail:
      "https://assets.untappd.com/site/brewery_logos/brewery-341365_12e41.jpeg",
    name: "Ozzie Orange Peel",
    style: "Wheat Beer",
    substyle: "Hefeweizen",
    breweryName: "ManaFirkin Brewing Co.",
    abv: 6.1,
    ibu: null,
    score: 3.61776,
    beerUrl:
      "https://untappd.com/b/manafirkin-brewing-co-ozzie-orange-peel/3798244",
    breweryUrl: "https://untappd.com/w/manafirkin-brewing-co/341365",
    isVip: false,
    id: 3798244,
    table: 20,
  },
  {
    thumbnail:
      "https://assets.untappd.com/site/brewery_logos/brewery-341365_12e41.jpeg",
    name: "Good KARMAmile",
    style: "Wheat Beer",
    substyle: "American Pale Wheat",
    breweryName: "ManaFirkin Brewing Co.",
    abv: 6,
    ibu: null,
    score: 3.64179,
    beerUrl:
      "https://untappd.com/b/manafirkin-brewing-co-good-karmamile/2118336",
    breweryUrl: "https://untappd.com/w/manafirkin-brewing-co/341365",
    isVip: false,
    id: 2118336,
    table: 20,
  },
  {
    thumbnail:
      "https://assets.untappd.com/site/brewery_logos/brewery-405858_94c00.jpeg",
    name: "Maya Double IPA",
    style: "IPA",
    substyle: "Imperial / Double",
    breweryName: "Montclair Brewery",
    abv: 7,
    ibu: null,
    score: 3.70367,
    beerUrl: "https://untappd.com/b/montclair-brewery-maya-double-ipa/4755210",
    breweryUrl: "https://untappd.com/w/montclair-brewery/405858",
    isVip: false,
    id: 4755210,
    table: 58,
  },
  {
    thumbnail:
      "https://assets.untappd.com/site/brewery_logos/brewery-405858_94c00.jpeg",
    name: "National Emergency",
    style: "IPA",
    substyle: "New England / Hazy",
    breweryName: "Montclair Brewery",
    abv: 7.8,
    ibu: null,
    score: 3.62372,
    beerUrl:
      "https://untappd.com/b/montclair-brewery-national-emergency/4291085",
    breweryUrl: "https://untappd.com/w/montclair-brewery/405858",
    isVip: false,
    id: 4291085,
    table: 58,
  },
  {
    thumbnail:
      "https://assets.untappd.com/site/beer_logos/beer-3858184_584fd_sm.jpeg",
    name: "Black Is Beautiful W/Baobab",
    style: "Stout",
    substyle: "Imperial / Double",
    breweryName: "Montclair Brewery",
    abv: 9.1,
    ibu: null,
    score: 3.78673,
    beerUrl:
      "https://untappd.com/b/montclair-brewery-black-is-beautiful-w-baobab/3858184",
    breweryUrl: "https://untappd.com/w/montclair-brewery/405858",
    isVip: false,
    id: 3858184,
    table: 58,
  },
  {
    thumbnail:
      "https://assets.untappd.com/site/beer_logos/beer-4213739_a69cb_sm.jpeg",
    name: "Four City Stout",
    style: "Stout",
    substyle: "Irish Dry",
    breweryName: "Four City Brewing Company",
    abv: 4.7,
    ibu: null,
    score: 3.76486,
    beerUrl:
      "https://untappd.com/b/four-city-brewing-company-four-city-stout/4213739",
    breweryUrl: "https://untappd.com/w/four-city-brewing-company/401658",
    isVip: false,
    id: 4213739,
    table: 49,
  },
  {
    thumbnail:
      "https://assets.untappd.com/site/beer_logos/beer-3693748_f3599_sm.jpeg",
    name: "The Miseducation of Loral Hops",
    style: "IPA",
    substyle: "American",
    breweryName: "Four City Brewing Company",
    abv: 7,
    ibu: null,
    score: 3.89988,
    beerUrl:
      "https://untappd.com/b/four-city-brewing-company-the-miseducation-of-loral-hops/3693748",
    breweryUrl: "https://untappd.com/w/four-city-brewing-company/401658",
    isVip: false,
    id: 3693748,
    table: 49,
  },
  {
    thumbnail:
      "https://assets.untappd.com/site/beer_logos/beer-5210369_8bf93_sm.jpeg",
    name: "Breaker Bar",
    style: "IPA",
    substyle: "New England / Hazy",
    breweryName: "Gearblock Brewing Company",
    abv: 7,
    ibu: null,
    score: 3.71506,
    beerUrl:
      "https://untappd.com/b/gearblock-brewing-company-breaker-bar/5210369",
    breweryUrl: "https://untappd.com/w/gearblock-brewing-company/398869",
    isVip: false,
    id: 5210369,
    table: 17,
  },
  {
    thumbnail:
      "https://assets.untappd.com/site/beer_logos/beer-5210389_4a621_sm.jpeg",
    name: "K-Turn",
    style: "Kölsch",
    breweryName: "Gearblock Brewing Company",
    abv: 4.5,
    ibu: null,
    score: 3.71291,
    beerUrl: "https://untappd.com/b/gearblock-brewing-company-k-turn/5210389",
    breweryUrl: "https://untappd.com/w/gearblock-brewing-company/398869",
    isVip: false,
    id: 5210389,
    table: 17,
  },
  {
    thumbnail:
      "https://assets.untappd.com/site/brewery_logos/brewery-227511_33b6a.jpeg",
    name: "Mil-Spec Black IPA",
    style: "IPA",
    substyle: "Black / Cascadian Dark Ale",
    breweryName: "Backward Flag Brewing Co",
    abv: 7.3,
    ibu: null,
    score: 3.75383,
    beerUrl:
      "https://untappd.com/b/backward-flag-brewing-co-mil-spec-black-ipa/1392054",
    breweryUrl: "https://untappd.com/w/backward-flag-brewing-co/227511",
    isVip: false,
    id: 1392054,
    table: 50,
  },
  {
    thumbnail:
      "https://assets.untappd.com/site/brewery_logos/brewery-227511_33b6a.jpeg",
    name: "Oak Armored Ale",
    style: "Pale Ale",
    substyle: "American",
    breweryName: "Backward Flag Brewing Co",
    abv: 7,
    ibu: null,
    score: 3.64552,
    beerUrl:
      "https://untappd.com/b/backward-flag-brewing-co-oak-armored-ale/2024751",
    breweryUrl: "https://untappd.com/w/backward-flag-brewing-co/227511",
    isVip: false,
    id: 2024751,
    table: 50,
  },
  {
    thumbnail:
      "https://assets.untappd.com/site/beer_logos/beer-5048444_b56fd_sm.jpeg",
    name: "Stout De Muerto",
    style: "Stout",
    substyle: "Milk / Sweet",
    breweryName: "902 Brewing",
    abv: 7.1,
    ibu: null,
    score: 3.72835,
    beerUrl: "https://untappd.com/b/902-brewing-stout-de-muerto/5048444",
    breweryUrl: "https://untappd.com/w/902-brewing/42165",
    isVip: false,
    id: 5048444,
    table: 40,
  },
  {
    thumbnail:
      "https://assets.untappd.com/site/beer_logos/beer-5193470_b1d81_sm.jpeg",
    name: "8 Anniversary Premium Lager",
    style: "Lager",
    substyle: "Dortmunder / Export",
    breweryName: "902 Brewing",
    abv: 5.5,
    ibu: 15,
    score: 3.68317,
    beerUrl:
      "https://untappd.com/b/902-brewing-8-anniversary-premium-lager/5193470",
    breweryUrl: "https://untappd.com/w/902-brewing/42165",
    isVip: false,
    id: 5193470,
    table: 40,
  },
  {
    thumbnail:
      "https://assets.untappd.com/site/beer_logos/beer-4001156_3f2e2_sm.jpeg",
    name: "Blackberry",
    style: "Cider",
    substyle: "Other Fruit",
    breweryName: "Downeast Cider House",
    abv: 5,
    ibu: null,
    score: 3.90516,
    beerUrl: "https://untappd.com/b/downeast-cider-house-blackberry/4001156",
    breweryUrl: "https://untappd.com/w/downeast-cider-house/22486",
    isVip: false,
    id: 4001156,
    table: 1,
  },
  {
    thumbnail:
      "https://assets.untappd.com/site/beer_logos/beer-3886141_3fd99_sm.jpeg",
    name: "Strawberry",
    style: "Cider",
    substyle: "Other Fruit",
    breweryName: "Downeast Cider House",
    abv: 5,
    ibu: null,
    score: 3.97398,
    beerUrl: "https://untappd.com/b/downeast-cider-house-strawberry/3886141",
    breweryUrl: "https://untappd.com/w/downeast-cider-house/22486",
    isVip: false,
    id: 3886141,
    table: 1,
  },
  {
    thumbnail:
      "https://assets.untappd.com/site/beer_logos/beer-3351998_871d8_sm.jpeg",
    name: "Guava Cider",
    style: "Cider",
    substyle: "Other Fruit",
    breweryName: "Ace Cider (The California Cider Company)",
    abv: 5,
    ibu: null,
    score: 3.97058,
    beerUrl:
      "https://untappd.com/b/ace-cider-the-california-cider-company-guava-cider/3351998",
    breweryUrl:
      "https://untappd.com/w/ace-cider-the-california-cider-company/331",
    isVip: false,
    id: 3351998,
    table: 3,
  },
  {
    thumbnail:
      "https://assets.untappd.com/site/beer_logos/beer-3865969_96591_sm.jpeg",
    name: "Mango Cider",
    style: "Cider",
    substyle: "Other Fruit",
    breweryName: "Ace Cider (The California Cider Company)",
    abv: 5,
    ibu: null,
    score: 3.85804,
    beerUrl:
      "https://untappd.com/b/ace-cider-the-california-cider-company-mango-cider/3865969",
    breweryUrl:
      "https://untappd.com/w/ace-cider-the-california-cider-company/331",
    isVip: false,
    id: 3865969,
    table: 3,
  },
  {
    thumbnail:
      "https://assets.untappd.com/site/beer_logos/beer-602768_e191e_sm.jpeg",
    name: "Ace Pineapple Cider",
    style: "Cider",
    substyle: "Other Fruit",
    breweryName: "Ace Cider (The California Cider Company)",
    abv: 5,
    ibu: null,
    score: 3.78589,
    beerUrl:
      "https://untappd.com/b/ace-cider-the-california-cider-company-ace-pineapple-cider/602768",
    breweryUrl:
      "https://untappd.com/w/ace-cider-the-california-cider-company/331",
    isVip: false,
    id: 602768,
    table: 3,
  },
  {
    thumbnail:
      "https://assets.untappd.com/site/beer_logos/beer-5839_f51fd_sm.jpeg",
    name: "Banana Bread Beer",
    style: "Fruit Beer",
    breweryName: "Eagle Brewery (formerly Charles Wells)",
    abv: 5.2,
    ibu: 18,
    score: 3.55456,
    beerUrl:
      "https://untappd.com/b/eagle-brewery-formerly-charles-wells-banana-bread-beer/5839",
    breweryUrl:
      "https://untappd.com/w/eagle-brewery-formerly-charles-wells/1348",
    isVip: false,
    id: 5839,
  },
  {
    thumbnail:
      "https://assets.untappd.com/site/beer_logos/beer-130571_147d9_sm.jpeg",
    name: "Young's Double Chocolate Stout",
    style: "Stout",
    substyle: "Milk / Sweet",
    breweryName: "Eagle Brewery (formerly Charles Wells)",
    abv: 5.2,
    ibu: 25,
    score: 3.67179,
    beerUrl:
      "https://untappd.com/b/eagle-brewery-formerly-charles-wells-young-s-double-chocolate-stout/130571",
    breweryUrl:
      "https://untappd.com/w/eagle-brewery-formerly-charles-wells/1348",
    isVip: false,
    id: 130571,
  },
  {
    thumbnail:
      "https://assets.untappd.com/site/beer_logos/beer-4514812_99665_sm.jpeg",
    name: "Introspection",
    style: "IPA",
    substyle: "Triple",
    breweryName: "Tripping Animals Brewing Co.",
    abv: 10,
    ibu: null,
    score: 4.02886,
    beerUrl:
      "https://untappd.com/b/tripping-animals-brewing-co-introspection/4514812",
    breweryUrl: "https://untappd.com/w/tripping-animals-brewing-co/309155",
    isVip: false,
    id: 4514812,
    table: 5,
  },
  {
    thumbnail:
      "https://assets.untappd.com/site/beer_logos/beer-5152695_6434a_sm.jpeg",
    name: "Shergar",
    style: "Stout",
    substyle: "Irish Dry",
    breweryName: "Tripping Animals Brewing Co.",
    abv: 5,
    ibu: null,
    score: 3.72195,
    beerUrl:
      "https://untappd.com/b/tripping-animals-brewing-co-shergar/5152695",
    breweryUrl: "https://untappd.com/w/tripping-animals-brewing-co/309155",
    isVip: false,
    id: 5152695,
    table: 5,
  },
  {
    thumbnail:
      "https://assets.untappd.com/site/beer_logos/beer-3828725_4947c_sm.jpeg",
    name: "Triple Berry Pie Piggy (Pie Series)",
    style: "Sour",
    substyle: "Smoothie / Pastry",
    breweryName: "Tripping Animals Brewing Co.",
    abv: 6,
    ibu: null,
    score: 4.10247,
    beerUrl:
      "https://untappd.com/b/tripping-animals-brewing-co-triple-berry-pie-piggy-pie-series/3828725",
    breweryUrl: "https://untappd.com/w/tripping-animals-brewing-co/309155",
    isVip: false,
    id: 3828725,
    table: 5,
  },
  {
    thumbnail:
      "https://assets.untappd.com/site/beer_logos/beer-3640207_ad68f_sm.jpeg",
    name: "SLUSHY XXL Nimbus 2000",
    style: "Sour",
    substyle: "Fruited Berliner Weisse",
    breweryName: "450 North Brewing Company",
    abv: 5.86,
    ibu: null,
    score: 4.14154,
    beerUrl:
      "https://untappd.com/b/450-north-brewing-company-slushy-xxl-nimbus-2000/3640207",
    breweryUrl: "https://untappd.com/w/450-north-brewing-company/40301",
    isVip: false,
    id: 3640207,
    table: 4,
  },
  {
    thumbnail:
      "https://assets.untappd.com/site/brewery_logos/brewery-40301_8c13b.jpeg",
    name: "SLUSHY XL Hawaiian Dole Whip",
    style: "Sour",
    substyle: "Smoothie / Pastry",
    breweryName: "450 North Brewing Company",
    abv: 5.3,
    ibu: null,
    score: 3.95954,
    beerUrl:
      "https://untappd.com/b/450-north-brewing-company-slushy-xl-hawaiian-dole-whip/4970839",
    breweryUrl: "https://untappd.com/w/450-north-brewing-company/40301",
    isVip: false,
    id: 4970839,
    table: 4,
  },
  {
    thumbnail:
      "https://assets.untappd.com/site/brewery_logos/brewery-40301_8c13b.jpeg",
    name: "SLUSHY XL Cherry Cheesecake",
    style: "Sour",
    substyle: "Fruited",
    breweryName: "450 North Brewing Company",
    abv: 5.3,
    ibu: null,
    score: 3.98741,
    beerUrl:
      "https://untappd.com/b/450-north-brewing-company-slushy-xl-cherry-cheesecake/4934988",
    breweryUrl: "https://untappd.com/w/450-north-brewing-company/40301",
    isVip: false,
    id: 4934988,
    table: 4,
  },
  {
    thumbnail:
      "https://assets.untappd.com/site/beer_logos/beer-1944569_922f0_sm.jpeg",
    name: "Pineapple",
    style: "Cider",
    substyle: "Other Fruit",
    breweryName: "Downeast Cider House",
    abv: 5.1,
    ibu: null,
    score: 3.89649,
    beerUrl: "https://untappd.com/b/downeast-cider-house-pineapple/1944569",
    breweryUrl: "https://untappd.com/w/downeast-cider-house/22486",
    isVip: false,
    id: 1944569,
    table: 1,
  },
  {
    thumbnail:
      "https://assets.untappd.com/site/beer_logos/beer-1922515_5d7bc_sm.jpeg",
    name: "Spin IPA",
    style: "IPA",
    substyle: "Other",
    breweryName: "High Point Brewing Company (New Jersey)",
    abv: 7,
    ibu: 55,
    score: 3.74657,
    beerUrl:
      "https://untappd.com/b/high-point-brewing-company-new-jersey-spin-ipa/1922515",
    breweryUrl:
      "https://untappd.com/w/high-point-brewing-company-new-jersey/4233",
    isVip: false,
    id: 1922515,
    table: 38,
  },
  {
    thumbnail:
      "https://assets.untappd.com/site/beer_logos/beer-46871_33bbc_sm.jpeg",
    name: "Ramstein Double Platinum Blonde",
    style: "Bock",
    substyle: "Weizenbock",
    breweryName: "High Point Brewing Company (New Jersey)",
    abv: 7,
    ibu: null,
    score: 3.72263,
    beerUrl:
      "https://untappd.com/b/high-point-brewing-company-new-jersey-ramstein-double-platinum-blonde/46871",
    breweryUrl:
      "https://untappd.com/w/high-point-brewing-company-new-jersey/4233",
    isVip: false,
    id: 46871,
    table: 38,
  },
  {
    thumbnail:
      "https://assets.untappd.com/site/beer_logos/beer-159244_ce7a1_sm.jpeg",
    name: "Ramstein Imperial Pils",
    style: "Pilsner",
    substyle: "Imperial / Double",
    breweryName: "High Point Brewing Company (New Jersey)",
    abv: 7,
    ibu: 68,
    score: 3.55845,
    beerUrl:
      "https://untappd.com/b/high-point-brewing-company-new-jersey-ramstein-imperial-pils/159244",
    breweryUrl:
      "https://untappd.com/w/high-point-brewing-company-new-jersey/4233",
    isVip: false,
    id: 159244,
    table: 38,
  },
  {
    thumbnail:
      "https://assets.untappd.com/site/brewery_logos/brewery-80412_aace8.jpeg",
    name: "Blackflower AmLam Blend",
    style: "Wild Ale",
    substyle: "Other",
    breweryName: "Muckraker Beermaker",
    abv: 6,
    ibu: null,
    score: 3.72254,
    beerUrl:
      "https://untappd.com/b/muckraker-beermaker-blackflower-amlam-blend/5190167",
    breweryUrl: "https://untappd.com/w/muckraker-beermaker/80412",
    isVip: false,
    id: 5190167,
    table: 41,
  },
  {
    thumbnail:
      "https://assets.untappd.com/site/brewery_logos/brewery-80412_aace8.jpeg",
    name: "Hazen",
    style: "IPA",
    substyle: "New England / Hazy",
    breweryName: "Muckraker Beermaker",
    abv: 6,
    ibu: null,
    score: 3.87558,
    beerUrl: "https://untappd.com/b/muckraker-beermaker-hazen/1674832",
    breweryUrl: "https://untappd.com/w/muckraker-beermaker/80412",
    isVip: false,
    id: 1674832,
    table: 41,
  },
  {
    thumbnail:
      "https://assets.untappd.com/site/beer_logos/beer-1735167_b20e3_sm.jpeg",
    name: "King Gambrinus Belgian Tripel",
    style: "Belgian Tripel",
    breweryName: "Jersey Girl Brewing",
    abv: 10,
    ibu: null,
    score: 3.75635,
    beerUrl:
      "https://untappd.com/b/jersey-girl-brewing-king-gambrinus-belgian-tripel/1735167",
    breweryUrl: "https://untappd.com/w/jersey-girl-brewing/194453",
    isVip: false,
    id: 1735167,
    table: 60,
  },
  {
    thumbnail:
      "https://assets.untappd.com/site/beer_logos/beer-1767368_cd2cc_sm.jpeg",
    name: "Rake Breaker",
    style: "IPA",
    substyle: "American",
    breweryName: "Jersey Girl Brewing",
    abv: 6.5,
    ibu: null,
    score: 3.62452,
    beerUrl: "https://untappd.com/b/jersey-girl-brewing-rake-breaker/1767368",
    breweryUrl: "https://untappd.com/w/jersey-girl-brewing/194453",
    isVip: false,
    id: 1767368,
    table: 60,
  },
  {
    thumbnail:
      "https://assets.untappd.com/site/beer_logos/beer-5000247_f5566_sm.jpeg",
    name: "I LOVE YOU WITH ALL MY TART",
    style: "Sour",
    substyle: "Fruited",
    breweryName: "Evil Twin Brewing NYC",
    abv: 7,
    ibu: null,
    score: 4.08649,
    beerUrl:
      "https://untappd.com/b/evil-twin-brewing-nyc-i-love-you-with-all-my-tart/5000247",
    breweryUrl: "https://untappd.com/w/evil-twin-brewing-nyc/420055",
    isVip: false,
    id: 5000247,
    table: 43,
  },
  {
    thumbnail:
      "https://assets.untappd.com/site/beer_logos/beer-4236113_23d81_sm.jpeg",
    name: "GREENHOUSE ROTBIER CONDITIONED ON AMERICAN OAK FOUDRE",
    style: "Lager",
    substyle: "Red",
    breweryName: "Evil Twin Brewing NYC",
    abv: 5.4,
    ibu: null,
    score: 3.75997,
    beerUrl:
      "https://untappd.com/b/evil-twin-brewing-nyc-greenhouse-rotbier-conditioned-on-american-oak-foudre/4236113",
    breweryUrl: "https://untappd.com/w/evil-twin-brewing-nyc/420055",
    isVip: false,
    id: 4236113,
    table: 43,
  },
  {
    thumbnail:
      "https://assets.untappd.com/site/beer_logos/beer-5027406_a7378_sm.jpeg",
    name: "DR JEPPER CHERRY",
    style: "Sour",
    substyle: "Other",
    breweryName: "Evil Twin Brewing NYC",
    abv: 5.5,
    ibu: null,
    score: 3.59882,
    beerUrl:
      "https://untappd.com/b/evil-twin-brewing-nyc-dr-jepper-cherry/5027406",
    breweryUrl: "https://untappd.com/w/evil-twin-brewing-nyc/420055",
    isVip: false,
    id: 5027406,
    table: 43,
  },
  {
    thumbnail:
      "https://assets.untappd.com/site/beer_logos/beer-5201481_82beb_sm.jpeg",
    name: "BUZZIN’ CITRA + CASHMERE",
    style: "Pale Ale",
    substyle: "New England / Hazy",
    breweryName: "Evil Twin Brewing NYC",
    abv: 6,
    ibu: null,
    score: 3.73479,
    beerUrl:
      "https://untappd.com/b/evil-twin-brewing-nyc-buzzin-citra-cashmere/5201481",
    breweryUrl: "https://untappd.com/w/evil-twin-brewing-nyc/420055",
    isVip: false,
    id: 5201481,
    table: 43,
  },
  {
    thumbnail:
      "https://assets.untappd.com/site/beer_logos/beer-5209215_6a877_sm.jpeg",
    name: "Jurassic Bark",
    style: "IPA",
    substyle: "American",
    breweryName: "KCBC - Kings County Brewers Collective",
    abv: 7.2,
    ibu: null,
    score: 3.73479,
    beerUrl:
      "https://untappd.com/b/kcbc-kings-county-brewers-collective-jurassic-bark/5209215",
    breweryUrl:
      "https://untappd.com/w/kcbc-kings-county-brewers-collective/167520",
    isVip: false,
    id: 5209215,
    table: 37,
  },
  {
    thumbnail:
      "https://assets.untappd.com/site/brewery_logos/brewery-234267_0f9f5.jpeg",
    name: "Rosé",
    style: "Cider",
    substyle: "Rosé",
    breweryName: "Brooklyn Cider House",
    abv: 5.8,
    ibu: null,
    score: 3.74823,
    beerUrl: "https://untappd.com/b/brooklyn-cider-house-bch-rose/3157301",
    breweryUrl: "https://untappd.com/w/brooklyn-cider-house/234267",
    isVip: false,
    id: 3157301,
    table: 35,
  },
  {
    thumbnail:
      "https://assets.untappd.com/site/brewery_logos/brewery-234267_0f9f5.jpeg",
    name: "Half Sour",
    style: "Cider",
    substyle: "Traditional / Apfelwein",
    breweryName: "Brooklyn Cider House",
    abv: 5.8,
    ibu: null,
    score: 3.77289,
    beerUrl: "https://untappd.com/b/brooklyn-cider-house-half-sour/1541191",
    breweryUrl: "https://untappd.com/w/brooklyn-cider-house/234267",
    isVip: false,
    id: 1541191,
    table: 35,
  },
  {
    thumbnail:
      "https://assets.untappd.com/site/beer_logos/beer-1151251_34e82_sm.jpeg",
    name: "Grapefruit IPA",
    style: "Gluten-Free",
    breweryName: "Ghostfish Brewing Company",
    abv: 5.5,
    ibu: 85,
    score: 3.4052,
    beerUrl:
      "https://untappd.com/b/ghostfish-brewing-company-grapefruit-ipa/1151251",
    breweryUrl: "https://untappd.com/w/ghostfish-brewing-company/168106",
    isVip: false,
    id: 1151251,
    table: 36,
  },
  {
    thumbnail:
      "https://assets.untappd.com/site/beer_logos/beer-1898191_a3683_sm.jpeg",
    name: "Meteor Shower Blonde Ale",
    style: "Gluten-Free",
    breweryName: "Ghostfish Brewing Company",
    abv: 4.5,
    ibu: 15,
    score: 3.36151,
    beerUrl:
      "https://untappd.com/b/ghostfish-brewing-company-meteor-shower-blonde-ale/1898191",
    breweryUrl: "https://untappd.com/w/ghostfish-brewing-company/168106",
    isVip: false,
    id: 1898191,
    table: 36,
  },
  {
    thumbnail:
      "https://assets.untappd.com/site/beer_logos/beer-967407_3eeb8_sm.jpeg",
    name: "Shrouded Summit Belgian White Ale",
    style: "Gluten-Free",
    breweryName: "Ghostfish Brewing Company",
    abv: 4.5,
    ibu: 20,
    score: 3.37528,
    beerUrl:
      "https://untappd.com/b/ghostfish-brewing-company-shrouded-summit-belgian-white-ale/967407",
    breweryUrl: "https://untappd.com/w/ghostfish-brewing-company/168106",
    isVip: false,
    id: 967407,
    table: 36,
  },
  {
    thumbnail:
      "https://assets.untappd.com/site/beer_logos/beer-4818591_4348a_sm.jpeg",
    name: "I Really Like NJ",
    style: "Blonde Ale",
    breweryName: "Ludlam Island Brewery",
    abv: 5,
    ibu: null,
    score: 3.68133,
    beerUrl:
      "https://untappd.com/b/ludlam-island-brewery-i-really-like-nj/4818591",
    breweryUrl: "https://untappd.com/w/ludlam-island-brewery/211134",
    isVip: false,
    id: 4818591,
    table: 29,
  },
  {
    thumbnail:
      "https://assets.untappd.com/site/beer_logos/beer-2483089_440c6_sm.jpeg",
    name: "Water Guns and Rainbows",
    style: "IPA",
    substyle: "American",
    breweryName: "Ludlam Island Brewery",
    abv: 7.5,
    ibu: 30,
    score: 4.01289,
    beerUrl:
      "https://untappd.com/b/ludlam-island-brewery-water-guns-and-rainbows/2483089",
    breweryUrl: "https://untappd.com/w/ludlam-island-brewery/211134",
    isVip: false,
    id: 2483089,
    table: 29,
  },
  {
    thumbnail:
      "https://assets.untappd.com/site/beer_logos/beer-4570183_f9d59_sm.jpeg",
    name: "Slang Du Jour - Strawberry Rhubarb Cobbler",
    style: "Sour",
    substyle: "Smoothie / Pastry",
    breweryName: "Drekker Brewing Company",
    abv: 7.6,
    ibu: null,
    score: 4.09087,
    beerUrl:
      "https://untappd.com/b/drekker-brewing-company-slang-du-jour-strawberry-rhubarb-cobbler/4570183",
    breweryUrl: "https://untappd.com/w/drekker-brewing-company/161976",
    isVip: false,
    id: 4570183,
    table: 33,
  },
  {
    thumbnail:
      "https://assets.untappd.com/site/beer_logos/beer-205003_a19bb_sm.jpeg",
    name: "Peach",
    style: "Cider",
    substyle: "Other Fruit",
    breweryName: "Jack's Hard Cider",
    abv: 5,
    ibu: null,
    score: 3.52846,
    beerUrl: "https://untappd.com/b/jack-s-hard-cider-peach/205003",
    breweryUrl: "https://untappd.com/w/jack-s-hard-cider/4755",
    isVip: false,
    id: 205003,
    table: 32,
  },
  {
    thumbnail:
      "https://assets.untappd.com/site/beer_logos/beer-1372036_97e5d_sm.jpeg",
    name: "Pear",
    style: "Cider",
    substyle: "Perry",
    breweryName: "Jack's Hard Cider",
    abv: 5.5,
    ibu: null,
    score: 3.65537,
    beerUrl: "https://untappd.com/b/jack-s-hard-cider-pear/1372036",
    breweryUrl: "https://untappd.com/w/jack-s-hard-cider/4755",
    isVip: false,
    id: 1372036,
    table: 32,
  },
  {
    thumbnail:
      "https://assets.untappd.com/site/brewery_logos/brewery-135898_7ce8a.jpeg",
    name: "Feels Like Home Extra Juicy (Home Sweet Home)",
    style: "Cider",
    substyle: "Sweet",
    breweryName: "Artifact Cider Project",
    abv: 5,
    ibu: null,
    score: 3.73639,
    beerUrl:
      "https://untappd.com/b/artifact-cider-project-feels-like-home-extra-juicy-home-sweet-home/5023543",
    breweryUrl: "https://untappd.com/w/artifact-cider-project/135898",
    isVip: false,
    id: 5023543,
    table: 34,
  },
  {
    thumbnail:
      "https://assets.untappd.com/site/brewery_logos/brewery-135898_7ce8a.jpeg",
    name: "Feels Like Home Double Rum",
    style: "Cider",
    substyle: "Sweet",
    breweryName: "Artifact Cider Project",
    abv: 6.8,
    ibu: null,
    score: 3.74581,
    beerUrl:
      "https://untappd.com/b/artifact-cider-project-feels-like-home-double-rum/5023328",
    breweryUrl: "https://untappd.com/w/artifact-cider-project/135898",
    isVip: false,
    id: 5023328,
    table: 34,
  },
  {
    thumbnail:
      "https://assets.untappd.com/site/brewery_logos/brewery-135898_7ce8a.jpeg",
    name: "Feels Like Home Blueberry",
    style: "Cider",
    substyle: "Other Fruit",
    breweryName: "Artifact Cider Project",
    abv: 5,
    ibu: null,
    score: 3.7886,
    beerUrl:
      "https://untappd.com/b/artifact-cider-project-feels-like-home-blueberry/5023528",
    breweryUrl: "https://untappd.com/w/artifact-cider-project/135898",
    isVip: false,
    id: 5023528,
    table: 34,
  },
  {
    thumbnail:
      "https://assets.untappd.com/site/beer_logos/beer-4157952_6a630_sm.jpeg",
    name: "Surf! DDH West Coast IIPA",
    style: "IPA",
    substyle: "Imperial / Double",
    breweryName: "SingleCut Beersmiths",
    abv: 7.7,
    ibu: null,
    score: 3.88385,
    beerUrl:
      "https://untappd.com/b/singlecut-beersmiths-surf-ddh-west-coast-iipa/4157952",
    breweryUrl: "https://untappd.com/w/singlecut-beersmiths/16555",
    isVip: false,
    id: 4157952,
    table: 31,
  },
  {
    thumbnail:
      "https://assets.untappd.com/site/beer_logos/beer-2762455_9478d_sm.jpeg",
    name: "Jån Alpine White Lager",
    style: "Lager",
    substyle: "American",
    breweryName: "SingleCut Beersmiths",
    abv: 5.2,
    ibu: 14,
    score: 3.66169,
    beerUrl:
      "https://untappd.com/b/singlecut-beersmiths-jan-alpine-white-lager/2762455",
    breweryUrl: "https://untappd.com/w/singlecut-beersmiths/16555",
    isVip: false,
    id: 2762455,
    table: 31,
  },
  {
    thumbnail:
      "https://assets.untappd.com/site/beer_logos/beer-4302962_0ef68_sm.jpeg",
    name: "Stone Hazy IPA",
    style: "IPA",
    substyle: "American",
    breweryName: "Stone Brewing",
    abv: 6.7,
    ibu: 35,
    score: 3.74116,
    beerUrl: "https://untappd.com/b/stone-brewing-stone-hazy-ipa/4302962",
    breweryUrl: "https://untappd.com/w/stone-brewing/1204",
    isVip: false,
    id: 4302962,
    table: 7,
  },
  {
    thumbnail:
      "https://assets.untappd.com/site/beer_logos/beer-5079869_3db82_sm.jpeg",
    name: "Stone Delicious Double IPA",
    style: "IPA",
    substyle: "Imperial / Double",
    breweryName: "Stone Brewing",
    abv: 9.4,
    ibu: null,
    score: 3.9115,
    beerUrl:
      "https://untappd.com/b/stone-brewing-stone-delicious-double-ipa/5079869",
    breweryUrl: "https://untappd.com/w/stone-brewing/1204",
    isVip: false,
    id: 5079869,
    table: 7,
  },
  {
    thumbnail:
      "https://assets.untappd.com/site/beer_logos/beer-392748_9fec8_sm.jpeg",
    name: "Stone Delicious IPA",
    style: "IPA",
    substyle: "American",
    breweryName: "Stone Brewing",
    abv: 7.7,
    ibu: 75,
    score: 3.72984,
    beerUrl: "https://untappd.com/b/stone-brewing-stone-delicious-ipa/392748",
    breweryUrl: "https://untappd.com/w/stone-brewing/1204",
    isVip: false,
    id: 392748,
    table: 7,
  },
  {
    thumbnail:
      "https://assets.untappd.com/site/beer_logos/beer-4138953_4478f_sm.jpeg",
    name: "Baron Von Slamminhausen",
    style: "Kellerbier / Zwickelbier",
    breweryName: "Twin Elephant Brewing Company",
    abv: 5,
    ibu: null,
    score: 3.77326,
    beerUrl:
      "https://untappd.com/b/twin-elephant-brewing-company-baron-von-slamminhausen/4138953",
    breweryUrl: "https://untappd.com/w/twin-elephant-brewing-company/268063",
    isVip: false,
    id: 4138953,
    table: 23,
  },
  {
    thumbnail:
      "https://assets.untappd.com/site/beer_logos/beer-5193141_a4528_sm.jpeg",
    name: "Nosh: Galaxy & Zappa",
    style: "IPA",
    substyle: "American",
    breweryName: "Twin Elephant Brewing Company",
    abv: 7.1,
    ibu: null,
    score: 3.71614,
    beerUrl:
      "https://untappd.com/b/twin-elephant-brewing-company-nosh-galaxy-and-zappa/5193141",
    breweryUrl: "https://untappd.com/w/twin-elephant-brewing-company/268063",
    isVip: false,
    id: 5193141,
    table: 23,
  },
  {
    thumbnail:
      "https://assets.untappd.com/site/beer_logos/beer-4729819_97a81_sm.jpeg",
    name: "Star Jockey",
    style: "IPA",
    substyle: "New England / Hazy",
    breweryName: "Yards Brewing Co.",
    abv: 7.2,
    ibu: 33,
    score: 3.64916,
    beerUrl: "https://untappd.com/b/yards-brewing-co-star-jockey/4729819",
    breweryUrl: "https://untappd.com/w/yards-brewing-co/1383",
    isVip: false,
    id: 4729819,
    table: 6,
  },
  {
    thumbnail:
      "https://assets.untappd.com/site/beer_logos/beer-4508574_a4bab_sm.jpeg",
    name: "Level Up",
    style: "IPA",
    substyle: "American",
    breweryName: "Yards Brewing Co.",
    abv: 6.5,
    ibu: 50,
    score: 3.67876,
    beerUrl: "https://untappd.com/b/yards-brewing-co-level-up/4508574",
    breweryUrl: "https://untappd.com/w/yards-brewing-co/1383",
    isVip: false,
    id: 4508574,
    table: 6,
  },
  {
    thumbnail:
      "https://assets.untappd.com/site/beer_logos/beer-1650200_e7c59_sm.jpeg",
    name: "Hackensack Lager",
    style: "Lager",
    substyle: "Helles",
    breweryName: "Alementary Brewing Company",
    abv: 5.4,
    ibu: 28,
    score: 3.53501,
    beerUrl:
      "https://untappd.com/b/alementary-brewing-company-hackensack-lager/1650200",
    breweryUrl: "https://untappd.com/w/alementary-brewing-company/262130",
    isVip: false,
    id: 1650200,
    table: 30,
  },
  {
    thumbnail:
      "https://assets.untappd.com/site/beer_logos/beer-2944442_be09a_sm.jpeg",
    name: "Random Placement of Things",
    style: "Pale Ale",
    substyle: "American",
    breweryName: "Alementary Brewing Company",
    abv: 5.5,
    ibu: 25,
    score: 3.81027,
    beerUrl:
      "https://untappd.com/b/alementary-brewing-company-random-placement-of-things/2944442",
    breweryUrl: "https://untappd.com/w/alementary-brewing-company/262130",
    isVip: false,
    id: 2944442,
    table: 30,
  },
  {
    thumbnail:
      "https://assets.untappd.com/site/beer_logos/beer-5202721_20e5c_sm.jpeg",
    name: "Pai Mei",
    style: "Table Beer",
    breweryName: "Alternate Ending Beer Co.",
    abv: 2.6,
    ibu: null,
    score: 3.74092,
    beerUrl: "https://untappd.com/b/alternate-ending-beer-co-pai-mei/5202721",
    breweryUrl: "https://untappd.com/w/alternate-ending-beer-co/479687",
    isVip: false,
    id: 5202721,
    table: 42,
  },
  {
    thumbnail:
      "https://assets.untappd.com/site/beer_logos/beer-4039050_237c9_sm.jpeg",
    name: "The Royal Rug",
    style: "Pilsner",
    substyle: "German",
    breweryName: "Alternate Ending Beer Co.",
    abv: 4.8,
    ibu: null,
    score: 3.78347,
    beerUrl:
      "https://untappd.com/b/alternate-ending-beer-co-the-royal-rug/4039050",
    breweryUrl: "https://untappd.com/w/alternate-ending-beer-co/479687",
    isVip: false,
    id: 4039050,
    table: 42,
  },
  {
    thumbnail:
      "https://assets.untappd.com/site/brewery_logos/brewery-61894_c26b5.jpeg",
    name: "Parent Trap",
    style: "Porter",
    substyle: "American",
    breweryName: "Ashton Brewing",
    abv: 6.3,
    ibu: null,
    score: 3.78687,
    beerUrl: "https://untappd.com/b/ashton-brewing-parent-trap/4085728",
    breweryUrl: "https://untappd.com/w/ashton-brewing/61894",
    isVip: false,
    id: 4085728,
    table: 51,
  },
  {
    thumbnail:
      "https://assets.untappd.com/site/brewery_logos/brewery-61894_c26b5.jpeg",
    name: "Phantom Galaxy",
    style: "IPA",
    substyle: "New England / Hazy",
    breweryName: "Ashton Brewing",
    abv: 7.2,
    ibu: null,
    score: 3.73337,
    beerUrl: "https://untappd.com/b/ashton-brewing-phantom-galaxy/4054691",
    breweryUrl: "https://untappd.com/w/ashton-brewing/61894",
    isVip: false,
    id: 4054691,
    table: 51,
  },
  {
    thumbnail:
      "https://assets.untappd.com/site/beer_logos/beer-3498211_4096e_sm.jpeg",
    name: "Cryomax",
    style: "IPA",
    substyle: "New England / Hazy",
    breweryName: "Barrier Brewing Company",
    abv: 7,
    ibu: null,
    score: 3.83954,
    beerUrl: "https://untappd.com/b/barrier-brewing-company-cryomax/3498211",
    breweryUrl: "https://untappd.com/w/barrier-brewing-company/4171",
    isVip: false,
    id: 3498211,
    table: 28,
  },
  {
    thumbnail:
      "https://assets.untappd.com/site/beer_logos/beer-4628704_74c20_sm.jpeg",
    name: "King",
    style: "Lager",
    substyle: "American",
    breweryName: "Barrier Brewing Company",
    abv: 4.7,
    ibu: null,
    score: 3.6453,
    beerUrl: "https://untappd.com/b/barrier-brewing-company-king/4628704",
    breweryUrl: "https://untappd.com/w/barrier-brewing-company/4171",
    isVip: false,
    id: 4628704,
    table: 28,
  },
  {
    thumbnail:
      "https://assets.untappd.com/site/beer_logos/beer-697663_50eb3_sm.jpeg",
    name: "Money IPA (Dry-Hopped w/ Citra)",
    style: "IPA",
    substyle: "American",
    breweryName: "Barrier Brewing Company",
    abv: 7.3,
    ibu: null,
    score: 3.85974,
    beerUrl:
      "https://untappd.com/b/barrier-brewing-company-money-ipa-dry-hopped-w-citra/697663",
    breweryUrl: "https://untappd.com/w/barrier-brewing-company/4171",
    isVip: false,
    id: 697663,
    table: 28,
  },
  {
    thumbnail:
      "https://assets.untappd.com/site/beer_logos/beer-4469338_7aef5_sm.jpeg",
    name: "Our Sour #14: Sweet Dreams",
    style: "Sour",
    substyle: "Fruited",
    breweryName: "Barrier Brewing Company",
    abv: 5.7,
    ibu: null,
    score: 3.69245,
    beerUrl:
      "https://untappd.com/b/barrier-brewing-company-our-sour-14-sweet-dreams/4469338",
    breweryUrl: "https://untappd.com/w/barrier-brewing-company/4171",
    isVip: false,
    id: 4469338,
    table: 28,
  },
  {
    thumbnail:
      "https://assets.untappd.com/site/brewery_logos/brewery-BarrierBrewing_4171.png",
    name: "Ze German Series: Hefeweizen",
    style: "Wheat Beer",
    substyle: "Hefeweizen",
    breweryName: "Barrier Brewing Company",
    abv: 5.3,
    ibu: null,
    score: 3.67539,
    beerUrl:
      "https://untappd.com/b/barrier-brewing-company-ze-german-series-hefeweizen/4516356",
    breweryUrl: "https://untappd.com/w/barrier-brewing-company/4171",
    isVip: false,
    id: 4516356,
    table: 28,
  },
  {
    thumbnail:
      "https://assets.untappd.com/site/brewery_logos/brewery-BarrierBrewing_4171.png",
    name: "Ze German Series: Schwarzbier",
    style: "Schwarzbier",
    breweryName: "Barrier Brewing Company",
    abv: 5.3,
    ibu: null,
    score: 3.68687,
    beerUrl:
      "https://untappd.com/b/barrier-brewing-company-ze-german-series-schwarzbier/4486307",
    breweryUrl: "https://untappd.com/w/barrier-brewing-company/4171",
    isVip: false,
    id: 4486307,
    table: 28,
  },
  {
    thumbnail:
      "https://assets.untappd.com/site/beer_logos/beer-4544504_09124_sm.jpeg",
    name: "Pebb Light",
    style: "IPA",
    substyle: "Session",
    breweryName: "Bolero Snort Brewery",
    abv: 4.2,
    ibu: null,
    score: 3.6528,
    beerUrl: "https://untappd.com/b/bolero-snort-brewery-pebb-light/4544504",
    breweryUrl: "https://untappd.com/w/bolero-snort-brewery/6723",
    isVip: false,
    id: 4544504,
    table: 46,
  },
  {
    thumbnail:
      "https://assets.untappd.com/site/beer_logos/beer-3182280_1d887_sm.jpeg",
    name: "Sour Pasture Calves (Raspberry / Lime)",
    style: "Sour",
    substyle: "Fruited",
    breweryName: "Bolero Snort Brewery",
    abv: 5.9,
    ibu: null,
    score: 3.90084,
    beerUrl:
      "https://untappd.com/b/bolero-snort-brewery-sour-pasture-calves-raspberry-lime/3182280",
    breweryUrl: "https://untappd.com/w/bolero-snort-brewery/6723",
    isVip: false,
    id: 3182280,
    table: 46,
  },
  {
    thumbnail:
      "https://assets.untappd.com/site/beer_logos/beer-5199667_19494_sm.jpeg",
    name: "Hibernation",
    style: "Winter Ale",
    breweryName: "Bradley Brew Project",
    abv: 8.5,
    ibu: null,
    score: 3.59297,
    beerUrl: "https://untappd.com/b/bradley-brew-project-hibernation/5199667",
    breweryUrl: "https://untappd.com/w/bradley-brew-project/356747",
    isVip: false,
    id: 5199667,
    table: 22,
  },
  {
    thumbnail:
      "https://assets.untappd.com/site/beer_logos/beer-4088584_206d7_sm.jpeg",
    name: "Holiday Break",
    style: "IPA",
    substyle: "Imperial / Double New England / Hazy",
    breweryName: "Bradley Brew Project",
    abv: 8,
    ibu: null,
    score: 3.83626,
    beerUrl: "https://untappd.com/b/bradley-brew-project-holiday-break/4088584",
    breweryUrl: "https://untappd.com/w/bradley-brew-project/356747",
    isVip: false,
    id: 4088584,
    table: 22,
  },
  {
    thumbnail:
      "https://assets.untappd.com/site/beer_logos/beer-3090992_8d3d1_sm.jpeg",
    name: "Skator",
    style: "Bock",
    substyle: "Doppelbock",
    breweryName: "Bradley Brew Project",
    abv: 8,
    ibu: null,
    score: 3.74906,
    beerUrl: "https://untappd.com/b/bradley-brew-project-skator/3090992",
    breweryUrl: "https://untappd.com/w/bradley-brew-project/356747",
    isVip: false,
    id: 3090992,
    table: 22,
  },
  {
    thumbnail:
      "https://assets.untappd.com/site/beer_logos/beer-1441008_d2575_sm.jpeg",
    name: "Elvis Juice",
    style: "IPA",
    substyle: "American",
    breweryName: "BrewDog",
    abv: 6.5,
    ibu: 40,
    score: 3.71413,
    beerUrl: "https://untappd.com/b/brewdog-elvis-juice/1441008",
    breweryUrl: "https://untappd.com/w/brewdog/241",
    isVip: false,
    id: 1441008,
    table: 10,
  },
  {
    thumbnail:
      "https://assets.untappd.com/site/beer_logos/beer-3560731_00eff_sm.jpeg",
    name: "Hazy Jane",
    style: "IPA",
    substyle: "New England / Hazy",
    breweryName: "BrewDog",
    abv: 5,
    ibu: null,
    score: 3.68463,
    beerUrl: "https://untappd.com/b/brewdog-hazy-jane/3560731",
    breweryUrl: "https://untappd.com/w/brewdog/241",
    isVip: false,
    id: 3560731,
    table: 10,
  },
  {
    thumbnail:
      "https://assets.untappd.com/site/beer_logos/beer-5702_276fe_sm.jpeg",
    name: "Punk IPA",
    style: "IPA",
    substyle: "American",
    breweryName: "BrewDog",
    abv: 5.2,
    ibu: 35,
    score: 3.72266,
    beerUrl: "https://untappd.com/b/brewdog-punk-ipa/5702",
    breweryUrl: "https://untappd.com/w/brewdog/241",
    isVip: false,
    id: 5702,
    table: 10,
  },
  {
    thumbnail:
      "https://assets.untappd.com/site/beer_logos/beer-4455052_ce666_sm.jpeg",
    name: "Hellcat",
    style: "Lager",
    substyle: "IPL (India Pale Lager)",
    breweryName: "BrewDog",
    abv: 6,
    ibu: null,
    score: 3.69007,
    beerUrl: "https://untappd.com/b/brewdog-usa-hellcat/4455052",
    breweryUrl: "https://untappd.com/w/brewdog-usa/426759",
    isVip: false,
    id: 4455052,
    table: 10,
  },
  {
    thumbnail:
      "https://assets.untappd.com/site/beer_logos/beer-2337873_c47ac_sm.jpeg",
    name: "Heady Jams",
    style: "IPA",
    substyle: "Imperial / Double New England / Hazy",
    breweryName: "Brix City Brewing",
    abv: 8,
    ibu: null,
    score: 4.16138,
    beerUrl: "https://untappd.com/b/brix-city-brewing-heady-jams/2337873",
    breweryUrl: "https://untappd.com/w/brix-city-brewing/199006",
    isVip: false,
    id: 2337873,
    table: 21,
  },
  {
    thumbnail:
      "https://assets.untappd.com/site/beer_logos/beer-2249300_057ce_sm.jpeg",
    name: "Strawberry Jams",
    style: "IPA",
    substyle: "Imperial / Double Milkshake",
    breweryName: "Brix City Brewing",
    abv: 8,
    ibu: 50,
    score: 4.0583,
    beerUrl: "https://untappd.com/b/brix-city-brewing-strawberry-jams/2249300",
    breweryUrl: "https://untappd.com/w/brix-city-brewing/199006",
    isVip: false,
    id: 2249300,
    table: 21,
  },
  {
    thumbnail:
      "https://assets.untappd.com/site/beer_logos/beer-63631_eec08_sm.jpeg",
    name: "Boat Beer",
    style: "IPA",
    substyle: "Session",
    breweryName: "Carton Brewing Company",
    abv: 4.2,
    ibu: 35,
    score: 3.72382,
    beerUrl: "https://untappd.com/b/carton-brewing-company-boat-beer/63631",
    breweryUrl: "https://untappd.com/w/carton-brewing-company/9558",
    isVip: false,
    id: 63631,
    table: 27,
  },
  {
    thumbnail:
      "https://assets.untappd.com/site/beer_logos/beer-1006782_643a3_sm.jpeg",
    name: "Cosmonaut",
    style: "Stout",
    substyle: "Russian Imperial",
    breweryName: "Carton Brewing Company",
    abv: 10,
    ibu: 65,
    score: 4.0016,
    beerUrl: "https://untappd.com/b/carton-brewing-company-cosmonaut/1006782",
    breweryUrl: "https://untappd.com/w/carton-brewing-company/9558",
    isVip: false,
    id: 1006782,
    table: 27,
  },
  {
    thumbnail:
      "https://assets.untappd.com/site/beer_logos/beer-3819473_c5ad9_sm.jpeg",
    name: "Frusta",
    style: "Pilsner",
    substyle: "Italian",
    breweryName: "Carton Brewing Company",
    abv: 4.2,
    ibu: 20,
    score: 3.91695,
    beerUrl: "https://untappd.com/b/carton-brewing-company-frusta/3819473",
    breweryUrl: "https://untappd.com/w/carton-brewing-company/9558",
    isVip: false,
    id: 3819473,
    table: 27,
  },
  {
    thumbnail:
      "https://assets.untappd.com/site/brewery_logos/brewery-9558_d56c2.jpeg",
    name: "Turn Up the Hook Mosaic",
    style: "IPA",
    substyle: "Imperial / Double",
    breweryName: "Carton Brewing Company",
    abv: 8.5,
    ibu: null,
    score: 3.73681,
    beerUrl:
      "https://untappd.com/b/carton-brewing-company-turn-up-the-hook-mosaic/5211361",
    breweryUrl: "https://untappd.com/w/carton-brewing-company/9558",
    isVip: false,
    id: 5211361,
    table: 27,
  },
  {
    thumbnail:
      "https://assets.untappd.com/site/beer_logos/beer-4910907_ef287_sm.jpeg",
    name: "Awkward Tanlines",
    style: "Lager",
    substyle: "Vienna",
    breweryName: "Coastal Brew Works",
    abv: 5.3,
    ibu: 25,
    score: 3.76457,
    beerUrl:
      "https://untappd.com/b/coastal-brew-works-awkward-tanlines/4910907",
    breweryUrl: "https://untappd.com/w/coastal-brew-works/521557",
    isVip: false,
    id: 4910907,
    table: 45,
  },
  {
    thumbnail:
      "https://assets.untappd.com/site/beer_logos/beer-4839414_eea4c_sm.jpeg",
    name: "Building Sandcastles (Sabro & Motueka)",
    style: "IPA",
    substyle: "New England / Hazy",
    breweryName: "Coastal Brew Works",
    abv: 5,
    ibu: 30,
    score: 3.82944,
    beerUrl:
      "https://untappd.com/b/coastal-brew-works-building-sandcastles-sabro-and-motueka/4839414",
    breweryUrl: "https://untappd.com/w/coastal-brew-works/521557",
    isVip: false,
    id: 4839414,
    table: 45,
  },
  {
    thumbnail:
      "https://assets.untappd.com/site/beer_logos/beer-2810404_69dff_sm.jpeg",
    name: "Sundial Series- Sunset Sherbet Sour IPA",
    style: "IPA",
    substyle: "Sour",
    breweryName: "Czig Meister",
    abv: 6.2,
    ibu: 24,
    score: 3.95293,
    beerUrl: "https://untappd.com/b/czig-meister-sunset-sherbet/2810404",
    breweryUrl: "https://untappd.com/w/czig-meister/228703",
    isVip: false,
    id: 2810404,
    table: 26,
  },
  {
    thumbnail:
      "https://assets.untappd.com/site/beer_logos/beer-2507448_1a832_sm.jpeg",
    name: "Tiramisu Milk Porter",
    style: "Porter",
    substyle: "Other",
    breweryName: "Czig Meister",
    abv: 5.2,
    ibu: 15,
    score: 3.75287,
    beerUrl: "https://untappd.com/b/czig-meister-tiramisu-milk-porter/2507448",
    breweryUrl: "https://untappd.com/w/czig-meister/228703",
    isVip: false,
    id: 2507448,
    table: 26,
  },
  {
    thumbnail:
      "https://assets.untappd.com/site/beer_logos/beer-2270119_9484d_sm.jpeg",
    name: "New Jersey Ninja",
    style: "Gluten-Free",
    breweryName: "Departed Soles Brewing Company",
    abv: 4.8,
    ibu: null,
    score: 3.44805,
    beerUrl:
      "https://untappd.com/b/departed-soles-brewing-company-new-jersey-ninja/2270119",
    breweryUrl: "https://untappd.com/w/departed-soles-brewing-company/191666",
    isVip: false,
    id: 2270119,
    table: 16,
  },
  {
    thumbnail:
      "https://assets.untappd.com/site/beer_logos/beer-3032202_d657d_sm.jpeg",
    name: "S’mo ‘n Joe",
    style: "Stout",
    substyle: "Imperial / Double Milk",
    breweryName: "Departed Soles Brewing Company",
    abv: 9.3,
    ibu: null,
    score: 3.85065,
    beerUrl:
      "https://untappd.com/b/departed-soles-brewing-company-s-mo-n-joe/3032202",
    breweryUrl: "https://untappd.com/w/departed-soles-brewing-company/191666",
    isVip: false,
    id: 3032202,
    table: 16,
  },
  {
    thumbnail:
      "https://assets.untappd.com/site/brewery_logos/brewery-191666_9f53a.jpeg",
    name: "Wave Runnering",
    style: "Gluten-Free",
    breweryName: "Departed Soles Brewing Company",
    abv: 4.2,
    ibu: null,
    score: 3.70605,
    beerUrl:
      "https://untappd.com/b/departed-soles-brewing-company-wave-runnering/5082064",
    breweryUrl: "https://untappd.com/w/departed-soles-brewing-company/191666",
    isVip: false,
    id: 5082064,
    table: 16,
  },
  {
    thumbnail:
      "https://assets.untappd.com/site/brewery_logos/brewery-191666_9f53a.jpeg",
    name: "Winter Winter Liquid Dinner",
    style: "Winter Warmer",
    breweryName: "Departed Soles Brewing Company",
    abv: 8.7,
    ibu: null,
    score: 3.63752,
    beerUrl:
      "https://untappd.com/b/departed-soles-brewing-company-winter-winter-liquid-dinner/5217415",
    breweryUrl: "https://untappd.com/w/departed-soles-brewing-company/191666",
    isVip: false,
    id: 5217415,
    table: 16,
  },
  {
    thumbnail:
      "https://assets.untappd.com/site/beer_logos/beer-5168984_ec2a6_sm.jpeg",
    name: "Kite And Key",
    style: "IPA",
    substyle: "New England / Hazy",
    breweryName: "Double Tap Brewing",
    abv: 7,
    ibu: 6,
    score: 3.77387,
    beerUrl: "https://untappd.com/b/double-tap-brewing-kite-and-key/5168984",
    breweryUrl: "https://untappd.com/w/double-tap-brewing/409017",
    isVip: false,
    id: 5168984,
    table: 19,
  },
  {
    thumbnail:
      "https://assets.untappd.com/site/beer_logos/beer-2885132_5e528_sm.jpeg",
    name: "Uncanny Wit",
    style: "Wheat Beer",
    substyle: "Witbier / Blanche",
    breweryName: "Double Tap Brewing",
    abv: 5.6,
    ibu: 15,
    score: 3.70551,
    beerUrl: "https://untappd.com/b/double-tap-brewing-uncanny-wit/2885132",
    breweryUrl: "https://untappd.com/w/double-tap-brewing/409017",
    isVip: false,
    id: 2885132,
    table: 19,
  },
  {
    thumbnail:
      "https://assets.untappd.com/site/beer_logos/beer-4962512_cbf2a_sm.jpeg",
    name: "Clever Goldfinch Double IPA",
    style: "IPA",
    substyle: "Imperial / Double",
    breweryName: "Five Dimes Brewery",
    abv: 8.5,
    ibu: null,
    score: 3.72689,
    beerUrl:
      "https://untappd.com/b/five-dimes-brewery-clever-goldfinch-double-ipa/4962512",
    breweryUrl: "https://untappd.com/w/five-dimes-brewery/511459",
    isVip: false,
    id: 4962512,
    table: 18,
  },
  {
    thumbnail:
      "https://assets.untappd.com/site/beer_logos/beer-4588234_5af10_sm.jpeg",
    name: "Five Dimes Hard Seltzer",
    style: "Hard Seltzer",
    breweryName: "Five Dimes Brewery",
    abv: 5,
    ibu: null,
    score: 3.69971,
    beerUrl:
      "https://untappd.com/b/five-dimes-brewery-five-dimes-hard-seltzer/4588234",
    breweryUrl: "https://untappd.com/w/five-dimes-brewery/511459",
    isVip: false,
    id: 4588234,
    table: 18,
  },
  {
    thumbnail:
      "https://assets.untappd.com/site/beer_logos/beer-5141595_d04de_sm.jpeg",
    name: "Home For the Holidays Peppermint Porter",
    style: "Porter",
    substyle: "American",
    breweryName: "Five Dimes Brewery",
    abv: 6,
    ibu: null,
    score: 3.71508,
    beerUrl:
      "https://untappd.com/b/five-dimes-brewery-home-for-the-holidays-peppermint-porter/5141595",
    breweryUrl: "https://untappd.com/w/five-dimes-brewery/511459",
    isVip: false,
    id: 5141595,
    table: 18,
  },
  {
    thumbnail:
      "https://assets.untappd.com/site/beer_logos/beer-4938357_327b6_sm.jpeg",
    name: "Kinderkamack Kolsch",
    style: "Kölsch",
    breweryName: "Five Dimes Brewery",
    abv: 5.4,
    ibu: null,
    score: 3.70479,
    beerUrl:
      "https://untappd.com/b/five-dimes-brewery-kinderkamack-kolsch/4938357",
    breweryUrl: "https://untappd.com/w/five-dimes-brewery/511459",
    isVip: false,
    id: 4938357,
    table: 18,
  },
  {
    thumbnail:
      "https://assets.untappd.com/site/beer_logos/beer-4899139_75f44_sm.jpeg",
    name: "Our Riviera",
    style: "Stout",
    substyle: "Irish Dry",
    breweryName: "Icarus Brewing",
    abv: 6.9,
    ibu: null,
    score: 3.84633,
    beerUrl: "https://untappd.com/b/icarus-brewing-our-riviera/4899139",
    breweryUrl: "https://untappd.com/w/icarus-brewing/312465",
    isVip: false,
    id: 4899139,
    table: 15,
  },
  {
    thumbnail:
      "https://assets.untappd.com/site/beer_logos/beer-4846502_5062f_sm.jpeg",
    name: "Yacht All The Time",
    style: "IPA",
    substyle: "New England / Hazy",
    breweryName: "Icarus Brewing",
    abv: 6.5,
    ibu: null,
    score: 3.94547,
    beerUrl: "https://untappd.com/b/icarus-brewing-yacht-all-the-time/4846502",
    breweryUrl: "https://untappd.com/w/icarus-brewing/312465",
    isVip: false,
    id: 4846502,
    table: 15,
  },
  {
    thumbnail:
      "https://assets.untappd.com/site/beer_logos/beer-1804913_63d04_sm.jpeg",
    name: "Approved Stout",
    style: "Stout",
    substyle: "American",
    breweryName: "Interboro Spirits & Ales",
    abv: 5.5,
    ibu: null,
    score: 3.71364,
    beerUrl:
      "https://untappd.com/b/interboro-spirits-and-ales-approved-stout/1804913",
    breweryUrl: "https://untappd.com/w/interboro-spirits-ales/279573",
    isVip: false,
    id: 1804913,
    table: 14,
  },
  {
    thumbnail:
      "https://assets.untappd.com/site/beer_logos/beer-4692697_3c353_sm.jpeg",
    name: "Certified",
    style: "Lager",
    substyle: "Winter",
    breweryName: "Interboro Spirits & Ales",
    abv: 6.7,
    ibu: 27,
    score: 3.70256,
    beerUrl:
      "https://untappd.com/b/interboro-spirits-and-ales-certified/4692697",
    breweryUrl: "https://untappd.com/w/interboro-spirits-ales/279573",
    isVip: false,
    id: 4692697,
    table: 14,
  },
  {
    thumbnail:
      "https://assets.untappd.com/site/beer_logos/beer-4413377_bc2d2_sm.jpeg",
    name: "Light Works Mosaic",
    style: "Sour",
    substyle: "Other",
    breweryName: "Interboro Spirits & Ales",
    abv: 6,
    ibu: null,
    score: 3.56375,
    beerUrl:
      "https://untappd.com/b/interboro-spirits-and-ales-light-works-mosaic/4413377",
    breweryUrl: "https://untappd.com/w/interboro-spirits-ales/279573",
    isVip: false,
    id: 4413377,
    table: 14,
  },
  {
    thumbnail:
      "https://assets.untappd.com/site/beer_logos/beer-4487339_fa0c3_sm.jpeg",
    name: "Light Works Passionfruit",
    style: "Sour",
    substyle: "Other",
    breweryName: "Interboro Spirits & Ales",
    abv: 6,
    ibu: 15,
    score: 3.56375,
    beerUrl:
      "https://untappd.com/b/interboro-spirits-and-ales-light-works-passionfruit/4487339",
    breweryUrl: "https://untappd.com/w/interboro-spirits-ales/279573",
    isVip: false,
    id: 4487339,
    table: 14,
  },
  {
    thumbnail:
      "https://assets.untappd.com/site/beer_logos/beer-2600662_57896_sm.jpeg",
    name: "Angelica",
    style: "IPA",
    substyle: "American",
    breweryName: "Lord Hobo Brewing Co.",
    abv: 5.5,
    ibu: null,
    score: 3.71166,
    beerUrl: "https://untappd.com/b/lord-hobo-brewing-co-angelica/2600662",
    breweryUrl: "https://untappd.com/w/lord-hobo-brewing-co/199369",
    isVip: false,
    id: 2600662,
    table: 13,
  },
  {
    thumbnail:
      "https://assets.untappd.com/site/beer_logos/beer-1066203_644b4_sm.jpeg",
    name: "Boomsauce",
    style: "IPA",
    substyle: "Imperial / Double New England / Hazy",
    breweryName: "Lord Hobo Brewing Co.",
    abv: 8,
    ibu: 78,
    score: 3.90884,
    beerUrl: "https://untappd.com/b/lord-hobo-brewing-co-boomsauce/1066203",
    breweryUrl: "https://untappd.com/w/lord-hobo-brewing-co/199369",
    isVip: false,
    id: 1066203,
    table: 13,
  },
  {
    thumbnail:
      "https://assets.untappd.com/site/beer_logos/beer-4006585_a62a2_sm.jpeg",
    name: "Juice Lord",
    style: "IPA",
    substyle: "New England / Hazy",
    breweryName: "Lord Hobo Brewing Co.",
    abv: 6,
    ibu: null,
    score: 3.76137,
    beerUrl: "https://untappd.com/b/lord-hobo-brewing-co-juice-lord/4006585",
    breweryUrl: "https://untappd.com/w/lord-hobo-brewing-co/199369",
    isVip: false,
    id: 4006585,
    table: 13,
  },
  {
    thumbnail:
      "https://assets.untappd.com/site/beer_logos/beer-5163007_f6091_sm.jpeg",
    name: "Life Non-Alcoholic",
    style: "Non-Alcoholic Beer",
    substyle: "IPA",
    breweryName: "Lord Hobo Brewing Co.",
    abv: null,
    ibu: null,
    score: 3.65523,
    beerUrl:
      "https://untappd.com/b/lord-hobo-brewing-co-life-non-alcoholic/5163007",
    breweryUrl: "https://untappd.com/w/lord-hobo-brewing-co/199369",
    isVip: false,
    id: 5163007,
    table: 13,
  },
  {
    thumbnail:
      "https://assets.untappd.com/site/beer_logos/beer-3995799_588f9_sm.jpeg",
    name: "Drill Deeper",
    style: "IPA",
    substyle: "Imperial / Double",
    breweryName: "Magnify Brewing Company",
    abv: 9,
    ibu: null,
    score: 4.06932,
    beerUrl:
      "https://untappd.com/b/magnify-brewing-company-drill-deeper/3995799",
    breweryUrl: "https://untappd.com/w/magnify-brewing-company/193269",
    isVip: false,
    id: 3995799,
    table: 56,
  },
  {
    thumbnail:
      "https://assets.untappd.com/site/beer_logos/beer-3299200_ca67b_sm.jpeg",
    name: "Puzzle Pieces",
    style: "Sour",
    substyle: "Fruited",
    breweryName: "Magnify Brewing Company",
    abv: 8,
    ibu: null,
    score: 3.97993,
    beerUrl:
      "https://untappd.com/b/magnify-brewing-company-puzzle-pieces/3299200",
    breweryUrl: "https://untappd.com/w/magnify-brewing-company/193269",
    isVip: false,
    id: 3299200,
    table: 56,
  },
  {
    thumbnail:
      "https://assets.untappd.com/site/beer_logos/beer-1020968_ac04b_sm.jpeg",
    name: "Vine Shine",
    style: "IPA",
    substyle: "American",
    breweryName: "Magnify Brewing Company",
    abv: 6.5,
    ibu: 60,
    score: 3.81907,
    beerUrl: "https://untappd.com/b/magnify-brewing-company-vine-shine/1020968",
    breweryUrl: "https://untappd.com/w/magnify-brewing-company/193269",
    isVip: false,
    id: 1020968,
    table: 56,
  },
  {
    thumbnail:
      "https://assets.untappd.com/site/beer_logos/beer-5030280_661d3_sm.jpeg",
    name: "Key Lime Shape of Haze To Come",
    style: "IPA",
    substyle: "New England / Hazy",
    breweryName: "Neshaminy Creek Brewing Company",
    abv: 8.8,
    ibu: 26,
    score: 3.77169,
    beerUrl:
      "https://untappd.com/b/neshaminy-creek-brewing-company-key-lime-shape-of-haze-to-come/5030280",
    breweryUrl: "https://untappd.com/w/neshaminy-creek-brewing-company/13327",
    isVip: false,
    id: 5030280,
    table: 11,
  },
  {
    thumbnail:
      "https://assets.untappd.com/site/beer_logos/beer-3707475_3094c_sm.jpeg",
    name: "Warehouse Lager",
    style: "Lager",
    substyle: "Mexican",
    breweryName: "Neshaminy Creek Brewing Company",
    abv: 4.5,
    ibu: 18,
    score: 3.62249,
    beerUrl:
      "https://untappd.com/b/neshaminy-creek-brewing-company-warehouse-lager/3707475",
    breweryUrl: "https://untappd.com/w/neshaminy-creek-brewing-company/13327",
    isVip: false,
    id: 3707475,
    table: 11,
  },
  {
    thumbnail:
      "https://assets.untappd.com/site/beer_logos/beer-1191132_5113c_sm.jpeg",
    name: "08087",
    style: "Pale Ale",
    substyle: "American",
    breweryName: "Pinelands Brewing Company",
    abv: 6,
    ibu: null,
    score: 3.64085,
    beerUrl: "https://untappd.com/b/pinelands-brewing-company-08087/1191132",
    breweryUrl: "https://untappd.com/w/pinelands-brewing-company/16882",
    isVip: false,
    id: 1191132,
    table: 12,
  },
  {
    thumbnail:
      "https://assets.untappd.com/site/beer_logos/beer-3925862_bb2b3_sm.jpeg",
    name: "Alterior Motive",
    style: "Altbier",
    breweryName: "Pinelands Brewing Company",
    abv: 6.1,
    ibu: null,
    score: 3.71039,
    beerUrl:
      "https://untappd.com/b/pinelands-brewing-company-alterior-motive/3925862",
    breweryUrl: "https://untappd.com/w/pinelands-brewing-company/16882",
    isVip: false,
    id: 3925862,
    table: 12,
  },
  {
    thumbnail:
      "https://assets.untappd.com/site/beer_logos/beer-575918_75cd5_sm.jpeg",
    name: "Evan John Porter",
    style: "Porter",
    substyle: "Other",
    breweryName: "Pinelands Brewing Company",
    abv: 5.3,
    ibu: 15,
    score: 3.77836,
    beerUrl:
      "https://untappd.com/b/pinelands-brewing-company-evan-john-porter/575918",
    breweryUrl: "https://untappd.com/w/pinelands-brewing-company/16882",
    isVip: false,
    id: 575918,
    table: 12,
  },
  {
    thumbnail:
      "https://assets.untappd.com/site/beer_logos/beer-1368077_8a4be_sm.jpeg",
    name: "Swamp Donkey",
    style: "IPA",
    substyle: "American",
    breweryName: "Pinelands Brewing Company",
    abv: 6.7,
    ibu: null,
    score: 3.59821,
    beerUrl:
      "https://untappd.com/b/pinelands-brewing-company-swamp-donkey/1368077",
    breweryUrl: "https://untappd.com/w/pinelands-brewing-company/16882",
    isVip: false,
    id: 1368077,
    table: 12,
  },
  {
    thumbnail:
      "https://assets.untappd.com/site/beer_logos/beer-5045842_418ff_sm.jpeg",
    name: "Ian's Jubilee",
    style: "IPA",
    substyle: "American",
    breweryName: "River Horse Brewing Co.",
    abv: 7.8,
    ibu: 50,
    score: 3.7103,
    beerUrl:
      "https://untappd.com/b/river-horse-brewing-co-ian-s-jubilee/5045842",
    breweryUrl: "https://untappd.com/w/river-horse-brewing-co/1058",
    isVip: false,
    id: 5045842,
    table: 9,
  },
  {
    thumbnail:
      "https://assets.untappd.com/site/beer_logos/beer-1460561_e3eb7_sm.jpeg",
    name: "Roly Poly Pils",
    style: "Pilsner",
    substyle: "Czech",
    breweryName: "River Horse Brewing Co.",
    abv: 5.3,
    ibu: null,
    score: 3.43636,
    beerUrl:
      "https://untappd.com/b/river-horse-brewing-co-roly-poly-pils/1460561",
    breweryUrl: "https://untappd.com/w/river-horse-brewing-co/1058",
    isVip: false,
    id: 1460561,
    table: 9,
  },
  {
    thumbnail:
      "https://assets.untappd.com/site/beer_logos/beer-4689921_dfc6e_sm.jpeg",
    name: "Dolce Amore",
    style: "Stout",
    substyle: "Other",
    breweryName: "Seven Tribesmen Brewery",
    abv: 6.5,
    ibu: 30,
    score: 3.78102,
    beerUrl:
      "https://untappd.com/b/seven-tribesmen-brewery-dolce-amore/4689921",
    breweryUrl: "https://untappd.com/w/seven-tribesmen-brewery/459629",
    isVip: false,
    id: 4689921,
    table: 54,
  },
  {
    thumbnail:
      "https://assets.untappd.com/site/beer_logos/beer-4225945_3a264_sm.jpeg",
    name: "Pines Lake Pils",
    style: "Pilsner",
    substyle: "German",
    breweryName: "Seven Tribesmen Brewery",
    abv: 5.5,
    ibu: 33,
    score: 3.73397,
    beerUrl:
      "https://untappd.com/b/seven-tribesmen-brewery-pines-lake-pils/4225945",
    breweryUrl: "https://untappd.com/w/seven-tribesmen-brewery/459629",
    isVip: false,
    id: 4225945,
    table: 54,
  },
  {
    thumbnail:
      "https://assets.untappd.com/site/beer_logos/beer-5218163_a13ff_sm.jpeg",
    name: "Tipsy Badger",
    style: "Lager",
    substyle: "Dark",
    breweryName: "Seven Tribesmen Brewery",
    abv: 4.9,
    ibu: 22,
    score: 3.71498,
    beerUrl:
      "https://untappd.com/b/seven-tribesmen-brewery-tipsy-badger/5218163",
    breweryUrl: "https://untappd.com/w/seven-tribesmen-brewery/459629",
    isVip: false,
    id: 5218163,
    table: 54,
  },
  {
    thumbnail:
      "https://assets.untappd.com/site/beer_logos/beer-4145235_00ab5_sm.jpeg",
    name: "As Simple As Shadows?",
    style: "Lager",
    substyle: "Dark",
    breweryName: "The Seed: A Living Beer Project",
    abv: 5.4,
    ibu: null,
    score: 4.02454,
    beerUrl:
      "https://untappd.com/b/the-seed-a-living-beer-project-as-simple-as-shadows/4145235",
    breweryUrl: "https://untappd.com/w/the-seed-a-living-beer-project/386673",
    isVip: false,
    id: 4145235,
    table: 24,
  },
  {
    thumbnail:
      "https://assets.untappd.com/site/beer_logos/beer-5211087_26e66_sm.jpeg",
    name: "Lights Please 9",
    style: "IPA",
    substyle: "American",
    breweryName: "The Seed: A Living Beer Project",
    abv: 6,
    ibu: null,
    score: 3.73593,
    beerUrl:
      "https://untappd.com/b/the-seed-a-living-beer-project-lights-please-9/5211087",
    breweryUrl: "https://untappd.com/w/the-seed-a-living-beer-project/386673",
    isVip: false,
    id: 5211087,
    table: 24,
  },
  {
    thumbnail:
      "https://assets.untappd.com/site/beer_logos/beer-4900737_6de10_sm.jpeg",
    name: "Modern Rituals: Emergence",
    style: "Stout",
    substyle: "Imperial / Double",
    breweryName: "The Seed: A Living Beer Project",
    abv: 12.5,
    ibu: null,
    score: 3.9994,
    beerUrl:
      "https://untappd.com/b/the-seed-a-living-beer-project-modern-rituals-emergence/4900737",
    breweryUrl: "https://untappd.com/w/the-seed-a-living-beer-project/386673",
    isVip: false,
    id: 4900737,
    table: 24,
  },
  {
    thumbnail:
      "https://assets.untappd.com/site/beer_logos/beer-5077369_ca077_sm.jpeg",
    name: "Modern Rituals: Furtherance",
    style: "Stout",
    substyle: "Imperial / Double",
    breweryName: "The Seed: A Living Beer Project",
    abv: 13,
    ibu: null,
    score: 3.95656,
    beerUrl:
      "https://untappd.com/b/the-seed-a-living-beer-project-modern-rituals-furtherance/5077369",
    breweryUrl: "https://untappd.com/w/the-seed-a-living-beer-project/386673",
    isVip: false,
    id: 5077369,
    table: 24,
  },
  {
    thumbnail:
      "https://assets.untappd.com/site/beer_logos/beer-4726327_cb14b_sm.jpeg",
    name: "Modern Rituals: Hibernation",
    style: "Stout",
    substyle: "Imperial / Double Coffee",
    breweryName: "The Seed: A Living Beer Project",
    abv: 13.7,
    ibu: null,
    score: 4.02036,
    beerUrl:
      "https://untappd.com/b/the-seed-a-living-beer-project-modern-rituals-hibernation/4726327",
    breweryUrl: "https://untappd.com/w/the-seed-a-living-beer-project/386673",
    isVip: false,
    id: 4726327,
    table: 24,
  },
  {
    thumbnail:
      "https://assets.untappd.com/site/brewery_logos/brewery-56206_ba12a.jpeg",
    name: "Parkway Phantom",
    style: "Pale Ale",
    substyle: "Other",
    breweryName: "Toms River Brewing",
    abv: 6,
    ibu: 38,
    score: 3.73039,
    beerUrl: "https://untappd.com/b/toms-river-brewing-parkway-phantom/5204717",
    breweryUrl: "https://untappd.com/w/toms-river-brewing/56206",
    isVip: false,
    id: 5204717,
    table: 55,
  },
  {
    thumbnail:
      "https://assets.untappd.com/site/beer_logos/beer-4684618_f1880_sm.jpeg",
    name: "Hop Horizon IPA",
    style: "IPA",
    substyle: "American",
    breweryName: "Tröegs Independent Brewing",
    abv: 6.5,
    ibu: null,
    score: 3.75719,
    beerUrl:
      "https://untappd.com/b/troegs-independent-brewing-hop-horizon-ipa/4684618",
    breweryUrl: "https://untappd.com/w/troegs-independent-brewing/2583",
    isVip: false,
    id: 4684618,
    table: 8,
  },
  {
    thumbnail:
      "https://assets.untappd.com/site/beer_logos/beer-3841_64639_sm.jpeg",
    name: "Sunshine Pils",
    style: "Pilsner",
    substyle: "German",
    breweryName: "Tröegs Independent Brewing",
    abv: 4.5,
    ibu: 45,
    score: 3.44528,
    beerUrl:
      "https://untappd.com/b/troegs-independent-brewing-sunshine-pils/3841",
    breweryUrl: "https://untappd.com/w/troegs-independent-brewing/2583",
    isVip: false,
    id: 3841,
    table: 8,
  },
  {
    thumbnail:
      "https://assets.untappd.com/site/beer_logos/beer-4918643_93ebd_sm.jpeg",
    name: "Infinite Machine",
    style: "Pilsner",
    substyle: "Other",
    breweryName: "KCBC - Kings County Brewers Collective",
    abv: 4.8,
    ibu: null,
    score: 3.75999,
    beerUrl:
      "https://untappd.com/b/kcbc-kings-county-brewers-collective-infinite-machine/4918643",
    breweryUrl:
      "https://untappd.com/w/kcbc-kings-county-brewers-collective/167520",
    isVip: true,
    id: 4918643,
    table: 37,
  },
  {
    thumbnail:
      "https://assets.untappd.com/site/brewery_logos/brewery-417861_baea5.jpeg",
    name: "Hackensack Comet",
    style: "IPA",
    substyle: "Imperial / Double",
    breweryName: "Hackensack Brewing",
    abv: 8.1,
    ibu: null,
    score: 3.75568,
    beerUrl:
      "https://untappd.com/b/hackensack-brewing-hackensack-comet/4530095",
    breweryUrl: "https://untappd.com/w/hackensack-brewing/417861",
    isVip: true,
    id: 4530095,
    table: 57,
  },
  {
    thumbnail:
      "https://assets.untappd.com/site/brewery_logos/brewery-341365_12e41.jpeg",
    name: "Coconut Coffee Cobra Kai PA",
    style: "IPA",
    substyle: "American",
    breweryName: "ManaFirkin Brewing Co.",
    abv: null,
    ibu: null,
    score: 3.71618,
    beerUrl:
      "https://untappd.com/b/manafirkin-brewing-co-coconut-coffee-cobra-kai-pa/3233782",
    breweryUrl: "https://untappd.com/w/manafirkin-brewing-co/341365",
    isVip: true,
    id: 3233782,
    table: 20,
  },
  {
    thumbnail:
      "https://assets.untappd.com/site/brewery_logos/brewery-405858_94c00.jpeg",
    name: "Baobiere",
    style: "Golden Ale",
    breweryName: "Montclair Brewery",
    abv: 7.8,
    ibu: null,
    score: 3.66317,
    beerUrl: "https://untappd.com/b/montclair-brewery-baobiere/3209358",
    breweryUrl: "https://untappd.com/w/montclair-brewery/405858",
    isVip: true,
    id: 3209358,
    table: 58,
  },
  {
    thumbnail:
      "https://assets.untappd.com/site/beer_logos/beer-5146904_7a6a0_sm.jpeg",
    name: "Soaked Stave",
    style: "Stout",
    substyle: "Imperial / Double",
    breweryName: "Gearblock Brewing Company",
    abv: 10,
    ibu: null,
    score: 3.75807,
    beerUrl:
      "https://untappd.com/b/gearblock-brewing-company-soaked-stave/5146904",
    breweryUrl: "https://untappd.com/w/gearblock-brewing-company/398869",
    isVip: true,
    id: 5146904,
    table: 17,
  },
  {
    thumbnail:
      "https://assets.untappd.com/site/brewery_logos/brewery-227511_33b6a.jpeg",
    name: "Mama's Table",
    style: "Pumpkin / Yam Beer",
    breweryName: "Backward Flag Brewing Co",
    abv: 5.1,
    ibu: null,
    score: 3.82426,
    beerUrl:
      "https://untappd.com/b/backward-flag-brewing-co-mama-s-table/1290678",
    breweryUrl: "https://untappd.com/w/backward-flag-brewing-co/227511",
    isVip: true,
    id: 1290678,
    table: 50,
  },
  {
    thumbnail:
      "https://assets.untappd.com/site/beer_logos/beer-4437116_85bf5_sm.jpeg",
    name: "Peach Sour",
    style: "Sour",
    substyle: "Fruited",
    breweryName: "902 Brewing",
    abv: 4.5,
    ibu: null,
    score: 3.73102,
    beerUrl: "https://untappd.com/b/902-brewing-peach-sour/4437116",
    breweryUrl: "https://untappd.com/w/902-brewing/42165",
    isVip: true,
    id: 4437116,
    table: 40,
  },
  {
    thumbnail:
      "https://assets.untappd.com/site/beer_logos/beer-4398251_6ab55_sm.jpeg",
    name: "Who Loves Orange Soda?",
    style: "Sour",
    substyle: "Fruited",
    breweryName: "Tripping Animals Brewing Co.",
    abv: 6,
    ibu: null,
    score: 4.0334,
    beerUrl:
      "https://untappd.com/b/tripping-animals-brewing-co-who-loves-orange-soda/4398251",
    breweryUrl: "https://untappd.com/w/tripping-animals-brewing-co/309155",
    isVip: true,
    id: 4398251,
    table: 5,
  },
  {
    thumbnail:
      "https://assets.untappd.com/site/beer_logos/beer-5162691_68faf_sm.jpeg",
    name: "SLUSHY XL Ninja Mantis",
    style: "Sour",
    substyle: "Fruited",
    breweryName: "450 North Brewing Company",
    abv: null,
    ibu: null,
    score: 3.78714,
    beerUrl:
      "https://untappd.com/b/450-north-brewing-company-slushy-xl-ninja-mantis/5162691",
    breweryUrl: "https://untappd.com/w/450-north-brewing-company/40301",
    isVip: true,
    id: 5162691,
    table: 4,
  },
  {
    thumbnail:
      "https://assets.untappd.com/site/beer_logos/beer-5610_9e9da_sm.jpeg",
    name: "Ramstein Winter Wheat",
    style: "Bock",
    substyle: "Weizendoppelbock",
    breweryName: "High Point Brewing Company (New Jersey)",
    abv: 9.5,
    ibu: 25,
    score: 3.72537,
    beerUrl:
      "https://untappd.com/b/high-point-brewing-company-new-jersey-ramstein-winter-wheat/5610",
    breweryUrl:
      "https://untappd.com/w/high-point-brewing-company-new-jersey/4233",
    isVip: true,
    id: 5610,
    table: 38,
  },
  {
    thumbnail:
      "https://assets.untappd.com/site/brewery_logos/brewery-80412_aace8.jpeg",
    name: "Madman's Drum",
    style: "Brett Beer",
    breweryName: "Muckraker Beermaker",
    abv: 5,
    ibu: null,
    score: 3.7003,
    beerUrl: "https://untappd.com/b/muckraker-beermaker-madman-s-drum/5164967",
    breweryUrl: "https://untappd.com/w/muckraker-beermaker/80412",
    isVip: true,
    id: 5164967,
    table: 41,
  },
  {
    thumbnail:
      "https://assets.untappd.com/site/brewery_logos/brewery-194453_6a690.jpeg",
    name: "Shark Attack",
    style: "Red Ale",
    substyle: "Irish",
    breweryName: "Jersey Girl Brewing",
    abv: 4.5,
    ibu: null,
    score: 3.68462,
    beerUrl: "https://untappd.com/b/jersey-girl-brewing-shark-attack/4733940",
    breweryUrl: "https://untappd.com/w/jersey-girl-brewing/194453",
    isVip: true,
    id: 4733940,
    table: 60,
  },
  {
    thumbnail:
      "https://assets.untappd.com/site/beer_logos/beer-5201482_89daa_sm.jpeg",
    name: "YOU’RE MY MAIN SQUEEZE",
    style: "IPA",
    substyle: "Imperial / Double New England / Hazy",
    breweryName: "Evil Twin Brewing NYC",
    abv: 8,
    ibu: null,
    score: 3.70277,
    beerUrl:
      "https://untappd.com/b/evil-twin-brewing-nyc-you-re-my-main-squeeze/5201482",
    breweryUrl: "https://untappd.com/w/evil-twin-brewing-nyc/420055",
    isVip: true,
    id: 5201482,
    table: 43,
  },
  {
    thumbnail:
      "https://assets.untappd.com/site/brewery_logos/brewery-234267_0f9f5.jpeg",
    name: "Raw",
    style: "Cider",
    substyle: "Traditional / Apfelwein",
    breweryName: "Brooklyn Cider House",
    abv: 6.9,
    ibu: null,
    score: 3.49247,
    beerUrl: "https://untappd.com/b/brooklyn-cider-house-raw/2177865",
    breweryUrl: "https://untappd.com/w/brooklyn-cider-house/234267",
    isVip: true,
    id: 2177865,
    table: 35,
  },
  {
    thumbnail:
      "https://assets.untappd.com/site/beer_logos/beer-2359298_0be4b_sm.jpeg",
    name: "Thunder Jacket",
    style: "Stout",
    substyle: "Imperial / Double Milk",
    breweryName: "Ludlam Island Brewery",
    abv: 8,
    ibu: null,
    score: 4.09442,
    beerUrl:
      "https://untappd.com/b/ludlam-island-brewery-thunder-jacket/2359298",
    breweryUrl: "https://untappd.com/w/ludlam-island-brewery/211134",
    isVip: true,
    id: 2359298,
    table: 29,
  },
  {
    thumbnail:
      "https://assets.untappd.com/site/beer_logos/beer-5093218_66ac9_sm.jpeg",
    name: "Slang Du Jour - Strawberry Shortcake",
    style: "Sour",
    substyle: "Smoothie / Pastry",
    breweryName: "Drekker Brewing Company",
    abv: 5.9,
    ibu: null,
    score: 3.97732,
    beerUrl:
      "https://untappd.com/b/drekker-brewing-company-slang-du-jour-strawberry-shortcake/5093218",
    breweryUrl: "https://untappd.com/w/drekker-brewing-company/161976",
    isVip: true,
    id: 5093218,
    table: 33,
  },
  {
    thumbnail:
      "https://assets.untappd.com/site/beer_logos/beer-4880320_c5857_sm.jpeg",
    name: "Ice Ice PRRRTY - Guava, Lemon-Lime, Coconut",
    style: "Sour",
    substyle: "Fruited",
    breweryName: "Drekker Brewing Company",
    abv: 7,
    ibu: null,
    score: 4.10964,
    beerUrl:
      "https://untappd.com/b/drekker-brewing-company-ice-ice-prrrty-guava-lemon-lime-coconut/4880320",
    breweryUrl: "https://untappd.com/w/drekker-brewing-company/161976",
    isVip: true,
    id: 4880320,
    table: 33,
  },
  {
    thumbnail:
      "https://assets.untappd.com/site/beer_logos/beer-5098943_9b2a7_sm.jpeg",
    name: "Amp Punch Blackberry Fruited Sour",
    style: "Sour",
    substyle: "Fruited",
    breweryName: "SingleCut Beersmiths",
    abv: 4.2,
    ibu: 10,
    score: 3.66255,
    beerUrl:
      "https://untappd.com/b/singlecut-beersmiths-amp-punch-blackberry-fruited-sour/5098943",
    breweryUrl: "https://untappd.com/w/singlecut-beersmiths/16555",
    isVip: true,
    id: 5098943,
    table: 31,
  },
  {
    thumbnail:
      "https://assets.untappd.com/site/beer_logos/beer-2495079_311e3_sm.jpeg",
    name: "Stone ///Fear.Movie.Lions Double IPA",
    style: "IPA",
    substyle: "Imperial / Double New England / Hazy",
    breweryName: "Stone Brewing",
    abv: 8.5,
    ibu: 60,
    score: 3.89637,
    beerUrl:
      "https://untappd.com/b/stone-brewing-stone-fear-movie-lions-double-ipa/2495079",
    breweryUrl: "https://untappd.com/w/stone-brewing/1204",
    isVip: true,
    id: 2495079,
    table: 7,
  },
  {
    thumbnail:
      "https://assets.untappd.com/site/beer_logos/beer-1554567_d0b23_sm.jpeg",
    name: "Lil' Shimmy Ye'",
    style: "Pale Ale",
    substyle: "American",
    breweryName: "Twin Elephant Brewing Company",
    abv: 5.8,
    ibu: null,
    score: 3.98585,
    beerUrl:
      "https://untappd.com/b/twin-elephant-brewing-company-lil-shimmy-ye/1554567",
    breweryUrl: "https://untappd.com/w/twin-elephant-brewing-company/268063",
    isVip: true,
    id: 1554567,
    table: 23,
  },
  {
    thumbnail:
      "https://assets.untappd.com/site/beer_logos/beer-4839315_4f14b_sm.jpeg",
    name: "Hot Paprika",
    style: "Red Ale",
    substyle: "American Amber / Red",
    breweryName: "Seven Tribesmen Brewery",
    abv: 5,
    ibu: 43,
    score: 3.73167,
    beerUrl:
      "https://untappd.com/b/seven-tribesmen-brewery-hot-paprika/4839315",
    breweryUrl: "https://untappd.com/w/seven-tribesmen-brewery/459629",
    isVip: true,
    id: 4839315,
    table: 54,
  },
  {
    thumbnail:
      "https://assets.untappd.com/site/beer_logos/beer-4397792_da2d7_sm.jpeg",
    name: "Digital Delay",
    style: "IPA",
    substyle: "Imperial / Double New England / Hazy",
    breweryName: "Brix City Brewing",
    abv: 8,
    ibu: null,
    score: 3.9038,
    beerUrl: "https://untappd.com/b/brix-city-brewing-digital-delay/4397792",
    breweryUrl: "https://untappd.com/w/brix-city-brewing/199006",
    isVip: true,
    id: 4397792,
    table: 21,
  },
  {
    thumbnail:
      "https://assets.untappd.com/site/beer_logos/beer-4999803_d2654_sm.jpeg",
    name: "The Boot",
    style: "Pilsner",
    substyle: "Italian",
    breweryName: "Double Tap Brewing",
    abv: 5.5,
    ibu: 28,
    score: 3.72814,
    beerUrl: "https://untappd.com/b/double-tap-brewing-the-boot/4999803",
    breweryUrl: "https://untappd.com/w/double-tap-brewing/409017",
    isVip: true,
    id: 4999803,
    table: 19,
  },
  {
    thumbnail:
      "https://assets.untappd.com/site/beer_logos/beer-3743588_72402_sm.jpeg",
    name: "Pound of Feathers",
    style: "Pilsner",
    substyle: "Imperial / Double",
    breweryName: "Icarus Brewing",
    abv: 7.1,
    ibu: null,
    score: 3.80164,
    beerUrl: "https://untappd.com/b/icarus-brewing-pound-of-feathers/3743588",
    breweryUrl: "https://untappd.com/w/icarus-brewing/312465",
    isVip: true,
    id: 3743588,
    table: 15,
  },
  {
    thumbnail:
      "https://assets.untappd.com/site/beer_logos/beer-2433486_175d8_sm.jpeg",
    name: "Unholy Ritual",
    style: "Belgian Quadrupel",
    breweryName: "Czig Meister",
    abv: 9.4,
    ibu: 21,
    score: 3.76951,
    beerUrl: "https://untappd.com/b/czig-meister-unholy-ritual/2433486",
    breweryUrl: "https://untappd.com/w/czig-meister/228703",
    isVip: true,
    id: 2433486,
    table: 26,
  },
  {
    thumbnail:
      "https://assets.untappd.com/site/brewery_logos/brewery-56206_ba12a.jpeg",
    name: "Stick Toss",
    style: "Kölsch",
    breweryName: "Toms River Brewing",
    abv: 5,
    ibu: 18,
    score: 3.6619,
    beerUrl: "https://untappd.com/b/toms-river-brewing-stick-toss/5066963",
    breweryUrl: "https://untappd.com/w/toms-river-brewing/56206",
    isVip: true,
    id: 5066963,
    table: 55,
  },
  {
    thumbnail:
      "https://assets.untappd.com/site/beer_logos/beer-1523851_1ff0f_sm.jpeg",
    name: "Crowning Achievement",
    style: "Stout",
    substyle: "Imperial / Double",
    breweryName: "Barrier Brewing Company",
    abv: 12,
    ibu: null,
    score: 3.90231,
    beerUrl:
      "https://untappd.com/b/barrier-brewing-company-crowning-achievement/1523851",
    breweryUrl: "https://untappd.com/w/barrier-brewing-company/4171",
    isVip: true,
    id: 1523851,
    table: 28,
  },
  {
    thumbnail:
      "https://assets.untappd.com/site/beer_logos/beer-4570080_09156_sm.jpeg",
    name: "Pastrytonium",
    style: "Stout",
    substyle: "Imperial / Double Pastry",
    breweryName: "Magnify Brewing Company",
    abv: 12,
    ibu: null,
    score: 3.8975,
    beerUrl:
      "https://untappd.com/b/magnify-brewing-company-pastrytonium/4570080",
    breweryUrl: "https://untappd.com/w/magnify-brewing-company/193269",
    isVip: true,
    id: 4570080,
    table: 56,
  },
  {
    thumbnail:
      "https://assets.untappd.com/site/beer_logos/beer-4582953_4fda9_sm.jpeg",
    name: "Chuckleheads Part 6 (Citra/Galaxy)",
    style: "IPA",
    substyle: "Imperial / Double",
    breweryName: "Alternate Ending Beer Co.",
    abv: 8.2,
    ibu: null,
    score: 3.87155,
    beerUrl:
      "https://untappd.com/b/alternate-ending-beer-co-chuckleheads-part-6-citra-galaxy/4582953",
    breweryUrl: "https://untappd.com/w/alternate-ending-beer-co/479687",
    isVip: true,
    id: 4582953,
    table: 42,
  },
  {
    thumbnail:
      "https://assets.untappd.com/site/beer_logos/beer-5143273_fd6a9_sm.jpeg",
    name: "Colorado Common Folklore",
    style: "California Common",
    breweryName: "Alementary Brewing Company",
    abv: 5,
    ibu: 12,
    score: 3.71132,
    beerUrl:
      "https://untappd.com/b/alementary-brewing-company-colorado-common-folklore/5143273",
    breweryUrl: "https://untappd.com/w/alementary-brewing-company/262130",
    isVip: true,
    id: 5143273,
    table: 30,
  },
  {
    thumbnail:
      "https://assets.untappd.com/site/beer_logos/beer-2246027_500a4_sm.jpeg",
    name: "Unicorn Girls",
    style: "Pale Ale",
    substyle: "New England / Hazy",
    breweryName: "Bradley Brew Project",
    abv: 5.4,
    ibu: null,
    score: 3.86163,
    beerUrl: "https://untappd.com/b/bradley-brew-project-unicorn-girls/2246027",
    breweryUrl: "https://untappd.com/w/bradley-brew-project/356747",
    isVip: true,
    id: 2246027,
    table: 22,
  },
  {
    thumbnail:
      "https://assets.untappd.com/site/brewery_logos/brewery-61894_c26b5.jpeg",
    name: "Fraxinus In Mezcal Barrels",
    style: "Barleywine",
    substyle: "Other",
    breweryName: "Ashton Brewing",
    abv: 10.5,
    ibu: null,
    score: 3.73145,
    beerUrl:
      "https://untappd.com/b/ashton-brewing-fraxinus-in-mezcal-barrels/4770858",
    breweryUrl: "https://untappd.com/w/ashton-brewing/61894",
    isVip: true,
    id: 4770858,
    table: 51,
  },
  {
    thumbnail:
      "https://assets.untappd.com/site/beer_logos/beer-5119051_6bdfa_sm.jpeg",
    name: "Bergen County Bull Stout : Banana Foster (2022)",
    style: "Stout",
    substyle: "Imperial / Double",
    breweryName: "Bolero Snort Brewery",
    abv: 11.3,
    ibu: null,
    score: 3.7856,
    beerUrl:
      "https://untappd.com/b/bolero-snort-brewery-bergen-county-bull-stout-banana-foster-2022/5119051",
    breweryUrl: "https://untappd.com/w/bolero-snort-brewery/6723",
    isVip: true,
    id: 5119051,
    table: 46,
  },
  {
    thumbnail:
      "https://assets.untappd.com/site/beer_logos/beer-4606421_75b74_sm.jpeg",
    name: "TURBINES & Blackbirds",
    style: "Stout",
    substyle: "Imperial / Double Pastry",
    breweryName: "Wild East Brewing Co.",
    abv: 10.2,
    ibu: 65,
    score: 3.75946,
    beerUrl:
      "https://untappd.com/b/wild-east-brewing-co-turbines-and-blackbirds/4606421",
    breweryUrl: "https://untappd.com/w/wild-east-brewing-co/391055",
    isVip: true,
    id: 4606421,
  },
  {
    thumbnail:
      "https://assets.untappd.com/site/beer_logos/beer-5030289_efff4_sm.jpeg",
    name: "Rough Puff",
    style: "Stout",
    substyle: "Imperial / Double Pastry",
    breweryName: "Neshaminy Creek Brewing Company",
    abv: 12.5,
    ibu: 17,
    score: 3.87439,
    beerUrl:
      "https://untappd.com/b/neshaminy-creek-brewing-company-rough-puff/5030289",
    breweryUrl: "https://untappd.com/w/neshaminy-creek-brewing-company/13327",
    isVip: true,
    id: 5030289,
    table: 11,
  },
  {
    thumbnail:
      "https://assets.untappd.com/site/brewery_logos/brewery-16882_6c563.jpeg",
    name: "What Flavor Is Haze",
    style: "IPA",
    substyle: "New England / Hazy",
    breweryName: "Pinelands Brewing Company",
    abv: 8.3,
    ibu: null,
    score: 3.6915,
    beerUrl:
      "https://untappd.com/b/pinelands-brewing-company-what-flavor-is-haze/3824184",
    breweryUrl: "https://untappd.com/w/pinelands-brewing-company/16882",
    isVip: true,
    id: 3824184,
    table: 12,
  },
  {
    thumbnail:
      "https://assets.untappd.com/site/brewery_logos/brewery-426759_28567.jpeg",
    name: "Hazy Jane Mango",
    style: "IPA",
    substyle: "New England / Hazy",
    breweryName: "BrewDog",
    abv: 7.2,
    ibu: null,
    score: 3.74509,
    beerUrl: "https://untappd.com/b/brewdog-usa-hazy-jane-mango/4480657",
    breweryUrl: "https://untappd.com/w/brewdog-usa/426759",
    isVip: true,
    id: 4480657,
    table: 10,
  },
  {
    thumbnail:
      "https://assets.untappd.com/site/brewery_logos/brewery-1058_97263.jpeg",
    name: "Cable Knit Hug",
    style: "Winter Warmer",
    breweryName: "River Horse Brewing Co.",
    abv: 6.6,
    ibu: 28,
    score: 3.68924,
    beerUrl:
      "https://untappd.com/b/river-horse-brewing-co-cable-knit-hug/5173285",
    breweryUrl: "https://untappd.com/w/river-horse-brewing-co/1058",
    isVip: true,
    id: 5173285,
    table: 9,
  },
  {
    thumbnail:
      "https://assets.untappd.com/site/beer_logos/beer-3757_1b370_sm.jpeg",
    name: "Nugget Nectar",
    style: "Red Ale",
    substyle: "Imperial / Double",
    breweryName: "Tröegs Independent Brewing",
    abv: 7.5,
    ibu: 93,
    score: 3.99336,
    beerUrl:
      "https://untappd.com/b/troegs-independent-brewing-nugget-nectar/3757",
    breweryUrl: "https://untappd.com/w/troegs-independent-brewing/2583",
    isVip: true,
    id: 3757,
    table: 8,
  },
  {
    thumbnail:
      "https://assets.untappd.com/site/beer_logos/beer-5141698_aae69_sm.jpeg",
    name: "Nautical Twilight",
    style: "Porter",
    substyle: "Coffee",
    breweryName: "Coastal Brew Works",
    abv: 6.5,
    ibu: 35,
    score: 3.80816,
    beerUrl:
      "https://untappd.com/b/coastal-brew-works-nautical-twilight/5141698",
    breweryUrl: "https://untappd.com/w/coastal-brew-works/521557",
    isVip: true,
    id: 5141698,
    table: 45,
  },
];
