export default {
  "Downeast Cider House": 1,
  "St. Killian": 2,
  "Ace Cider (The California Cider Company)": 3,
  "450 North Brewing Company": 4,
  "Tripping Animals Brewing Co.": 5,
  "Yards Brewing Co.": 6,
  "Stone Brewing": 7,
  "Tröegs Independent Brewing": 8,
  "River Horse Brewing Co.": 9,
  BrewDog: 10,
  "Neshaminy Creek Brewing Company": 11,
  "Pinelands Brewing Company": 12,
  "Lord Hobo Brewing Co.": 13,
  "Interboro Spirits & Ales": 14,
  "Icarus Brewing": 15,
  "Departed Soles Brewing Company": 16,
  "Gearblock Brewing Company": 17,
  "Five Dimes Brewery": 18,
  "Double Tap Brewing": 19,
  "ManaFirkin Brewing Co.": 20,
  "Brix City Brewing": 21,
  "Bradley Brew Project": 22,
  "Twin Elephant Brewing Company": 23,
  "The Seed: A Living Beer Project": 24,
  "Buttzville Brewing Company": 25,
  "Czig Meister": 26,
  "Carton Brewing Company": 27,
  "Barrier Brewing Company": 28,
  "Ludlam Island Brewery": 29,
  "Alementary Brewing Company": 30,
  "SingleCut Beersmiths": 31,
  "Jack's Hard Cider": 32,
  "Drekker Brewing Company": 33,
  "Artifact Cider Project": 34,
  "Brooklyn Cider House": 35,
  "Ghostfish Brewing Company": 36,
  "KCBC - Kings County Brewers Collective": 37,
  "High Point Brewing Company (New Jersey)": 38,
  "Ross Brewing Company": 39,
  "902 Brewing": 40,
  "Muckraker Beermaker": 41,
  "Alternate Ending Beer Co.": 42,
  "Evil Twin Brewing NYC": 43,
  "Skygazer Brewing Company": 44,
  "Coastal Brew Works": 45,
  "Bolero Snort Brewery": 46,
  "Craft Brew Candle": 47,
  "GT's Kombucha": 48,
  "Four City Brewing Company": 49,
  "Backward Flag Brewing Co": 50,
  "Ashton Brewing": 51,
  "Taproom Organics": 52,
  "Funny Water": 53,
  "Seven Tribesmen Brewery": 54,
  "Toms River Brewing": 55,
  "Magnify Brewing Company": 56,
  "Hackensack Brewing": 57,
  "Montclair Brewery": 58,
  "Birdsmouth Beer": 59,
  "Jersey Girl Brewing": 60,
  "Last Wave Brewing Co.": 61,
  "Wild Air Beerworks": 62,
} as const;
